### ISSUE TITLE
Modal window for worker groups not usable in dark theme Dashboard 

### ISSUE THREAD

**Issue by ewuknadierf** [gardener/dashboard#1017]
**How to categorize this issue?**

/area TODO
/kind bug
/priority 3

**What happened**:

In gardener dashboard i enabled dark theme (nice feature by the way).
In my cluster overview i cannot  configure the second group of my Workers properly, since they are rendered with a white background (see screenshot)
<img width="760" alt="Screenshot 2021-05-14 at 07 02 13" src="https://user-images.githubusercontent.com/1555662/118223844-61884200-b482-11eb-9bba-0d61ba350b77.png">
 

**What you expected to happen**:
- With normal light theme my two worker pools shown correctly.

**How to reproduce it (as minimally and precisely as possible)**:
- in gardener dashboard enable dark theme
- choose one of your clusters in your gardener project
- click _Configure Workers_

**Anything else we need to know?**:

**Environment**:
- OSX 11.3.1
- Browser Chrome 90.0.4430.212 and Vivaldi 3.8.2259.37 and Safari 14.1
- Gardener version: 1.49.1

**Comment by petersutter** [comment]
Hi @ewuknadierf, 

thank you for reporting this issue. We plan to release the dashboard 1.50.0 next week which will contain the fix https://github.com/gardener/dashboard/pull/1003 for this issue.
