### ISSUE TITLE
Project missing in list

### ISSUE THREAD

**Issue by fabianschwarzfritz** [gardener/dashboard#102]
I've created a project, called "EPS" this week. I am the creator of the project. However, I am not able to see the Project in the list of project on the left. Here's a screenshot:

![list-of-projects](https://user-images.githubusercontent.com/1759672/41027332-06d0dc40-6977-11e8-9450-1e228d4dca6c.png)

When I access the url of the project directly, in my case `/namespace/garden-eps/shoots/` I can access the project and see the list of clusters. The project is then still not displayed in the list of projects on the left. Here's what I see when accessing `/namespace/garden-eps/shoots/` directly:

![direct-url-access](https://user-images.githubusercontent.com/1759672/41027337-0abcb09a-6977-11e8-81e6-d329dc0166ba.png)

**Comment by vlerenc** [comment]
How did you create the project? There is no official programmatic API for creating projects.

**Comment by fabianschwarzfritz** [comment]
I have created the the project "EPS" via the Gardener UI, not via the programmatic API. 

I've also just had a quick call with @petersutter . I do have the same issue when creating a new project via the Gardener UI.

**Comment by vlerenc** [comment]
I do see your project and the annotations look OK (which doesn't surprise after your answer). Something with your name (with a hyphen)?

**Comment by petersutter** [comment]
yes the other members can see it.
he also has another project "ASDF123" that he also is the owner, which he can see..

**Comment by vlerenc** [comment]
OK, surprising. I can see both and also find no differences that would explain the behaviour on Cluster/NS level. Something in the dashboard itself?

**Comment by holgerkoser** [comment]
Scroll down?

**Comment by holgerkoser** [comment]
Or filter!

**Comment by fabianschwarzfritz** [comment]
Ouch, okay, scrolling did the trick. 

The idea never came to my mind, as the list is not "extending" to the bottom of the left. The list always shows the first three items, even if there is more space below to show more items. On mac I do not see scroll bars, the UI does not show any indication that there are more item either. With this behaviour it honestly looks to me as if there are no more items in the list.

I'll close this issue, as the project is in the list. The UI indication is still confusing in my opinion.

**Comment by holgerkoser** [comment]
I assume you have the general setting to not always show the scrollbar in macos
![image](https://user-images.githubusercontent.com/1574023/41031561-3a82751c-6981-11e8-8041-ef2665dcc1a3.png)
