### ISSUE TITLE
How to enable Custom Dashboard Fields

### ISSUE THREAD

**Issue by rufreakde** [gardener/dashboard#1029]
**What would you like to be added**:
Enhance the Readme Guide with some step by step instructions as it seems there are preconditions missing?

**Why is this needed**:
I tried to add "Custom Fields" in the administration view but it seems that I am not able to define any there.
<img width="764" alt="Screenshot 2021-05-27 at 16 09 50" src="https://user-images.githubusercontent.com/28104368/119841325-fe78bf80-bf05-11eb-8f42-b90d36fbb48a.png">

 HOW TO guide would be nice!

**Information**
I am Owner and Administrator of the Project. Also tried just to append /yaml on the administrator page url to see if I could edit it directly (similar to cluster ui pages) What do I miss here? I think the readme needs some more information.
/docs/usage/custom-fields.md

I could not find any HOW TO guide:
/docs/home/

**Comment by petersutter** [comment]
@rufreakde the documentation https://github.com/gardener/dashboard/blob/master/docs/usage/custom-fields.md should be complete, however I assume that your configuration could not be parsed.
Please check the javascript console of your browser for any errors. Currently we do not show any parsing errors on the UI as we also do not (yet) offer a UI for managing the custom fields

**Comment by rufreakde** [comment]
<img width="1599" alt="Screenshot 2021-05-27 at 16 37 42" src="https://user-images.githubusercontent.com/28104368/119845792-dd19d280-bf09-11eb-98a9-e73139da5f68.png">
Hi @petersutter ,
there is no parsing issue I am just not able to edit the project yaml?

**Comment by rufreakde** [comment]
Ah so you are not able to edit the project.yaml similar to the clusters? 
Okay that might be a nice hint (link to https://github.com/gardener/dashboard/blob/master/docs/usage/project-operations.md#download-kubeconfig-for-a-user as prerequisite) in the guide as it is stated there with some UI screenshots. I was not assuming I would have to change the resource via kubectl.

I will try that in a test project first thank you very much!

**Comment by petersutter** [comment]
https://github.com/gardener/dashboard/pull/1030

**Comment by grolu** [comment]
Fixed with PR #1030
