### ISSUE TITLE
Add support for application credentials for creating Openstack provider secrets

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/dashboard#1049]
**What would you like to be added**:
The form to enter the provider secret for Openstack should to be extended to include the fields `Application Credential ID` and `Application Credential Secret`. It should only be possible to fill either the fields `Technical User` and `Password` or these two new fields.

**Why is this needed**:
Application credentials will be supported in one of the next releases of the Openstack provider.
See https://github.com/gardener/gardener-extension-provider-openstack/pull/300

**Comment by grolu** [comment]
There is still a minor glitch but most of the PR is fine . As I want to do some validation logic cleanup anyway. Let's merge it now. I will add a separate PR later
