### ISSUE TITLE
Adapt EU Access dialogue

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/dashboard#1065]
**What would you like to be added**:

1. Remove the first tick and the corresponding text completely
2. Add the following text at the beginning of the text block: General restriction: Neither any personal data nor any customer data is used as name or in the content of Gardener or Kubernetes resources (e.g. Gardener project name or Kubernetes namespace, configMap or secret in Gardener or Kubernetes) 

**Why is this needed**:
We want to avoid, that stakeholders by not selecting the check box get the impression, that outside of EU Access we would allow personal data or any customer data to be used as name or in the content of Gardener or Kubernetes resources (e.g. Gardener project name or Kubernetes namespace, configMap or secret in Gardener or Kubernetes)

**Comment by petersutter** [comment]
@ThormaehlenFred the texts are configuration and not part of the dashboard. I will send you a PM with a link to the internal configuration
