### ISSUE TITLE
Allow the locking of clusters

### ISSUE THREAD

**Issue by berendt** [gardener/dashboard#1070]
**What would you like to be added**:

It should be possible to lock a cluster in a project in the UI so that no more changes can be made to it. Before making any changes, the user who created the lock should first have to remove it.

**Why is this needed**:

If several users are active in a project, this prevents accidental changes being made to a cluster.

**Comment by grolu** [comment]
@berendt yes, we could "lock" these clusters in the dashboard. However, Gardener needs to do the actual locking and the Dashboard only controls the status. Of course, it would also be possible to implement something in the Dashboard only, however it would still be possible to change the cluster via API.
@gardener/gardener-maintainers Do you plan to implement something like this?

**Comment by timebertt** [comment]
> @gardener/gardener-maintainers Do you plan to implement something like this?

No such thing is planned at the moment and I think it should not be done via the API.

**Comment by grolu** [comment]
/close
1. There is no locking planned from API side.
2. Locking the UI only is just a dirty hack as the cluster is not really locked which could give a false sense of security.
3. If you really need to prevent users from making changes to the clusters, just give them the viewer role onl which prevents them from changing stuff. The project owner can control who and when users have permission to change the clusters.

**Comment by berendt** [comment]
Why is it not planned from API side?

**Comment by grolu** [comment]
>Why is it not planned from API side?

@timebertt

**Comment by berendt** [comment]
On API side of OpenStack, locking of instances is possible as a protection against interference from other users. It is quite convenient when there are several equal users in a project to protect certain clusters from unauthorized actions.

Is also nice for change management in certain areas. The lock must be removed by a change before actions can be executed. After the change it will be locked again.

**Comment by berendt** [comment]
It is not primarily about the UI but about the lock on API level.

**Comment by timebertt** [comment]
Feel free to open an issue in g/g and start a discussion with a wider audience :)

**Comment by rfranzke** [comment]
TBH, I am with Tim here. Is there something comparable to this lock mechanism in Kubernetes? Can you help yourself with webhooks?
