### ISSUE TITLE
Add UI integration for the creation/management of Custom Fields

### ISSUE THREAD

**Issue by berendt** [gardener/dashboard#1071]
**What would you like to be added**:

It would be useful if any labels or tags could be assigned to a cluster. 

**Why is this needed**:

This allows you to map your own classification systems, etc. pp.

**Comment by petersutter** [comment]
Hi @berendt, have you checked if https://github.com/gardener/dashboard/blob/master/docs/usage/custom-fields.md fits your needs?

**Comment by berendt** [comment]
@petersutter I would just like to be able to attach any number of text strings to a cluster and then filter/search them. Without having to define special fields for this beforehand. These custom fields cannot be defined via UI either. A customer should be able to store the labels he needs for his workflows. We do not want to dictate these.

**Comment by petersutter** [comment]
@berendt yes currently you can only change the custom fields via the API, but this can also be done by the project owners, so you do not have to dictate these. It's just not that convenient as with the UI.
We haven't had the time yet to build a UI for it.

**Comment by berendt** [comment]
@petersutter Then let's rename this issue to "Add UI integration for the creation/management of Custom Fields"

**Comment by petersutter** [comment]
done :)

**Comment by grolu** [comment]
/close
fixed in #1926
