### ISSUE TITLE
add /healthz endpoint

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#108]
The dashboard should provide a simple health endpoint that returns 200 if the dashboard is up and running

**Comment by petersutter** [comment]
cc @rfranzke , @mandelsoft

**Comment by petersutter** [comment]
include also the results from gardener apiserver's healtz endpoint

**Comment by grolu** [comment]
Some thoughts on this
- We can only query the kubernetes api server healthz endpoint, as the gardener apiserver does not provide one
- If we want to do this, the dashboard healthz endpoint needs to be authenticated, as we need a bearer token for the kubernetes api rest call

You can find my current implementation in the referenced commit. @holgerkoser maybe you can give some feedback, as you suggested to make the call to the apiserver
