### ISSUE TITLE
Enhance Scrollbars in WebUI

### ISSUE THREAD

**Issue by tibeer** [gardener/dashboard#1085]
**What would you like to be added**:
Remove scroll bars from info fields, e.g. in cluster overview.

![Bildschirmfoto 2021-08-12 um 10 10 45](https://user-images.githubusercontent.com/39375770/129171395-8bbc6f1b-4869-4fc5-91df-a8c69156d545.png)

This also affects the Status popup as well as the readiness popups. Might affect some more.

**Why is this needed**:
If your screen is big enough this should not be viewed.

**Comment by holgerkoser** [comment]
This depends on your scrollbar system settings:

**_Show scroll bars:_ When scrolling**
<img width="600" alt="Screen Shot 2021-08-12 at 12 17 34" src="https://user-images.githubusercontent.com/1574023/129180687-d7611f3c-4e6d-42dc-99ba-f50af1b49f93.png">

**_Show scroll bars:_  Always**
<img width="600" alt="Screen Shot 2021-08-12 at 12 16 14" src="https://user-images.githubusercontent.com/1574023/129180691-4cbd4a37-ced6-4fc4-9cbd-e732e404bd09.png">

**Comment by holgerkoser** [comment]
We all use **When scrolling** but you are right and I took a closer look into our css code and found some usages of `overflow(-[xy])?: scroll` that causes all browsers to display scrollbars whether or not any content is actually clipped. 
 I think we can change the property to `auto` to let the browser decide if a scrollbar should be displayed or not. I create a PR https://github.com/gardener/dashboard/pull/1087 and discuss it with my colleagues.
