### ISSUE TITLE
Schroedinger's Superposition Pixel - Action Buttons and Ellipse

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#109]
A very tiny cosmetic issue: There is a width in which the buttons and the ellipse are shown together:
<img width="562" alt="41418453-01eb2080-6ff0-11e8-9ee1-3e216f6c1acb" src="https://user-images.githubusercontent.com/4974203/41419045-5c4e9934-6ff1-11e8-9c24-c3bd444eb11d.png">

**Comment by grolu** [comment]
Unfortunately, I wasn't able to reproduce the issue. I used Chrome dev tools and increased view size from 1264 to 1265 and the Ellipse gets replaced by the Action buttons (I don't see both of them).
Anyway, this would be a bug in the framework and nothing that we can fix in our code.
I will close the issue for now. Please re-open if you can reproduce the bug and we will have a closer look.
