### ISSUE TITLE
Make nodes CIDR defaults configurable for OpenStack

### ISSUE THREAD

**Issue by sku-sku** [gardener/dashboard#1099]
**What would you like to be added**:
Nodes CIDR is hard-coded to 10.250.0.0/16" for OpenStack. It would be great to have the default 
configurable in the cloud profile (or at least in the dashboard config)

**Why is this needed**:
For dedicated OpenStack installations there are other recommended defaults than the hardcoded one

**Comment by grolu** [comment]
We added an option to configure the default CIDR: https://github.com/gardener/dashboard/pull/1182

Is this sufficient or is there a need to make this configurable per landscape. Configuring it in the cloud profile would be even nicer as this makes it configurable for each installation individually. Moreover, the infrastructure extension could pick up the value. We discussed this before - it is anyway a bad design that all network values are defaulted by the infrastructure extension but we need to provide default values for the nodes / worker zone configuration. Adding it to the dashboard configuration also seems like a bad workaround. I vote for adding it to the cloud profile.
@rfranzke @marwinski @dkistner @DockToFuture @ScheererJ

**Comment by grolu** [comment]
We discussed this with @rfranzke. If we want to add this to the cloud profiles, Gardener should also implement some kind of defaulting. It is currently unclear if / when this will happen. I will move this issue to the icebox for now. If there really is demand for different CIDR configurations (depending on cloud profile), we could implement some intermediate solution, e.g. by annotating the cloud profile resource with a profile specific CIDR that the dashboard can pick up. Please respond to this ticket if this is (currently) a real requirement for you.
