### ISSUE TITLE
Add worker name validation

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#110]
Add worker name validation
- max length: 15
- has to be a valid subdomain name

> a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L127

see also Gardener worker validation
https://github.com/gardener/gardener/blob/3522923aa9af6a51ebfd3f460529b78f7bc2f85f/pkg/apis/garden/validation/validation.go#L1241-L1245

**Comment by grolu** [comment]
I Implemented the worker name validation. I followed the pattern that we implemented for the cluster name validation: Allow only alphanumeric characters and hyphens but no consecutive hyphens.
I have two questions for @rfranzke and @vlerenc:
- Are consecutive hyphens forbidden for worker names, too?
- While looking at the validation code in the gardener apiserver, I only found validation checks for valid DNS1123 subdomain, however this check allows dots (.) in the name. We currently do not allow this in the dashboard, but it looks to me as this is not catched by the apiserver. Is this an issue or can we allow this also in the dashboard?

**Comment by vlerenc** [comment]
cc @dkistner, @mvladev 

1. I don't think so. Double hyphens are primarily used as separators in NS by Gardener. Worker pool names don't end up in NS, afaik.
2. Hmm... I don't know either. While I understand that dots are allowed when checking for DNS subdomain compliance, I am not sure what would happen if you allow them in worker pool names (maybe used somewhere for separation in Gardener?). I would keep your check in the Dashboard (safer this way and "less hierarchical") and open a ticket on Gardener with that question, clarifying whether dots should be forbidden in Gardener (would be my tendency, allow less until somebody argues to need more) or allowed in the Dashboard.

**Comment by grolu** [comment]
Alright, I removed the consecutive hyphens check for workers. Considering dots in shoot / worker names: It seems like there is a bug in the gardener validation, as they validate DNS1123 **subdomain**, however they should check that the name is a valid DNS1123 **label**. This will lead to an error during creation, the same goes for worker names. I opened a ticket on the gardener project: https://github.com/gardener/gardener/issues/253
