### ISSUE TITLE
dashboard creates unnecessary SecretBinding while creating a DNS Secret

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#1155]
**What would you like to be added**:
Currently the Shoot accepts a SecretBinding only for the cloudprovider/infrastructure secret (`.spec.secretBindingName`). DNS Secrets are referenced without a SecretBinding. Hence, the SecretBinding that the dashboard currently creates on new DNS Secret creation is unnecessary and only helps the dashboard to show this Secret in the Secrets page.

Ref https://github.com/gardener/gardener/issues/3846.

**Why is this needed**:
To do not have a SecretBinding that is not actually used by the Gardener API itself (but only helps the dashboard to display the Secret).

**Comment by grolu** [comment]
Yes, I know that the SecretBinding Resource is "unnecessary" and cannot be used in Gardener. However there are two reasons why we have it that way

1) It keeps dashboard logic simpler, we can reuse logic and do not have to separate ways of handling the same thing (we would need to introduce workarounds / switches in the code)
2) We discussed this with @timuthy and we all agreed that it is not nice that Gardener has different ways of referencing secrets so I still think that this is a bug / missing feature in Gardener API and we therefore have no plans to change this in the dashboard.

**Comment by grolu** [comment]
@ialidzhikov One question that just came to me is if this will continue to work in the future. In your code 

https://github.com/gardener/dashboard/pull/1154/files#diff-7d578522ece4144f0f9f643a1188a8b2fb014341d663d9c4ed88d25fb9079283R94-R112

I can see that with the current changes, the `secretbinding.provider.type` is set to the DNS Provider type, e.g. `aws-route53`. Will this be rejected by Gardener as this is no valid infrastructure secret type? If so, we have a serious problem here.

**Comment by ialidzhikov** [comment]
No, as of today it won’t be rejected.

**Comment by grolu** [comment]
Okay thank you for the confirmation. I understand, that the _current_ plans are not to introduce secret bindings for the DNS use case. I will discuss this with the team and @rfranzke in our next sync. However, if we would remove this I want it to be discussed thoroughly. I don't want to remove it now (with significant effort, including migration) and have to re-introduce it later.
