### ISSUE TITLE
Improve success/error indication

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1159]
**What would you like to be added**:
E.g. in case a user has a red–green color blindness it is hard to distinguish the error / success state of the readiness chips.
E.g. the fine lines could be made thicker in case of an error or an ❗ icon could be added, similar to the status. 
It was reported that the green on the status is recognized better.

**Why is this needed**:

**Comment by grolu** [comment]
+1 for adding an icon

**Comment by petersutter** [comment]
oh I wasn't aware, I guess we can close this one then?
