### ISSUE TITLE
it is not clear that OpenStack means "SAP OpenStack" in the UI

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#116]
some stakeholder asks if it possible to have a cluster from SAP. They didn't get 
that "OpenStack" is the SAP infrastructure.

May we should change the label.

<img width="1099" alt="bildschirmfoto 2018-06-26 um 11 07 46" src="https://user-images.githubusercontent.com/1155039/41901662-cd3d1366-7931-11e8-9f95-1f8c6f2342ad.png">

**Comment by vlerenc** [comment]
This is an Open Source project, so we can't add SAP directly. Please see also https://github.com/gardener/dashboard/issues/18 where this topic is also mentioned. This is a duplicate.
