### ISSUE TITLE
Use gardenlogin kubeconfig instead of <shoot>.kubeconfig on cluster details page

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1168]
**What would you like to be added**:
Use gardenlogin kubeconfig instead of <shoot>.kubeconfig on cluster details page.

This requires the user to install [g/gardenlogin](https://github.com/gardener/gardenlogin) credential plugin. A hint, similar to the one for kubelogin on the Accounts page should be displayed.

**Why is this needed**:
The gardenlogin kubeconfig does not pose the risk of leaking credentials as it does not contain any. An example kubeconfig can be seen here https://github.com/gardener/gardenlogin/blob/master/example/01-kubeconfig.yaml

**Comment by vlerenc** [comment]
@petersutter Thanks, plus: We will need it anyway as we plan to get rid of static token cluster-admin kubeconfigs and then people will configure OIDC, but to set up RBAC properly, this will then be the only way to gain initial access.
