### ISSUE TITLE
Can specify invalid volume size via Gardener dashboard

### ISSUE THREAD

**Issue by jkafka23** [gardener/dashboard#118]
Hi colleagues, 

when creating a new cluster with Gardener 1.14.0 , I can specify a volume size of 1Gi which leads to the following error: 

"Shoot.garden.sapcloud.io "jasonktest" is invalid: spec.cloud.aws.workers[0].volumeSize: Invalid value: "1Gi": volume size must be at least 20Gi
"

If the minimum size is known in advance, one could restrict the UI input to this, i.e. I should not be able to enter anything lesser then 20 Gi. 

Cheers
Jason

**Comment by freegroup** [comment]
may you can use the gardener configmap for this. There are already some cloud provider
values stored. Maybe it is the right place to add some constraints.

<img width="664" alt="bildschirmfoto 2018-07-03 um 09 03 56" src="https://user-images.githubusercontent.com/1155039/42203919-843cf180-7ea0-11e8-998c-e0928dc4e480.png">

**Comment by petersutter** [comment]
@rfranzke does it make sense to have the minimumVolumeSize as part of the cloud profile?

**Comment by rfranzke** [comment]
Yes, I guess it makes sense.

**Comment by grolu** [comment]
will be done as part of #457
