### ISSUE TITLE
The generation fields `metadata.generation` and `status.observedGeneration` go out of sync when editing the Shoot yaml from inside the Gardener UI

### ISSUE THREAD

**Issue by bollmann** [gardener/dashboard#1197]
**What happened**:
Our gardener cluster shoot's `metadata.generation` and `status.observedGeneration` fields went out of sync. When changing the yaml from inside the Gardener UI and then pressing the button "Reconcile" only the generation in field `metadata.generation` gets incremented. However, the generation in field `status.observedGeneration` stays the same.

**What you expected to happen**:

Shouldn't both of these generations be incremented? At least having different generations inside the two fields breaks the SAP-internal LSS/`iacman2`/iac system that expects both versions to be the same.

Moreover, I wonder what to do once both of these generational fields carry different values. How would one go about making them the same again?

**How to reproduce it (as minimally and precisely as possible)**:

Change a cluster shoot's yaml from inside the Gardener UI, save it and then hit the button "Reconcile". Observe how this only increments the value of field `metadata.generation`, but not also the value of field `status.observedGeneration`.

**Environment**:

**Comment by dguendisch** [comment]
It's perfectly fine for these values to differ for a certain amount of time. Nearly everything in K8s is async and will be acted upon eventually. Please read up on these fields (e.g. start with https://stackoverflow.com/a/47101418).
Not related to the dashboard.
/close
