### ISSUE TITLE
unable to read full error message in shoot YAML editor

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#123]
I'm unable to read the full error message in the shoot editor.

In the cluster overview the error display toggles from small tooltip to an dialog if the error message
is longer than XY.  Maybe this could be a good UX pattern for the YAML editor as well.

<img width="1049" alt="bildschirmfoto 2018-07-04 um 11 49 41" src="https://user-images.githubusercontent.com/1155039/42270327-d7602522-7f80-11e8-8de3-a960498e2a1c.png">

**Comment by grolu** [comment]
Solved with new yaml editor.
