### ISSUE TITLE
missing project name in the kubeconfig.yaml of the technical user

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#125]
The kubeconfig.yaml of the technical user didn't contain the related *project* name.
Maybe the *name* entry in the kubeconfig can contain this as seen in the normal kubeconfig.yaml of a Cluster. Without them I have no idea to which project the kubeconfig belongs to.

kubeconfig.yaml of the technical user:
<img width="280" alt="bildschirmfoto 2018-07-05 um 14 51 06" src="https://user-images.githubusercontent.com/1155039/42324395-5d0d9820-8063-11e8-843c-f8f458533c5f.png">

kubeconfig.yaml of a normal cluster:
<img width="333" alt="bildschirmfoto 2018-07-05 um 14 55 49" src="https://user-images.githubusercontent.com/1155039/42324475-9db8e4ce-8063-11e8-9dee-3132a84d901d.png">

**Comment by vlerenc** [comment]
Good idea.
