### ISSUE TITLE
Add ability to trigger control plane migration from the gardener dashboard

### ISSUE THREAD

**Issue by plkokanov** [gardener/dashboard#1256]
**What would you like to be added**:
Shoot operators to have an easy way of triggering control plane migration directly from the dashboard. Perhaps it could be done via a button in the dashboard section where the seed is specified, similar to what is used to configure the `Workers`, `Purpose`, `Access Restrictions`, `Addons` and so on.

This button should only be visible/usable by ~gardener operators~ users that have permissions to update the `shoots/binding` subresource. Currently, only users that have the `gardener.cloud:admin` role can update the `shoots/binding` subresource. However, if necessary we could temporarily extend the project owners and project admins to also have the required permissions.

**Why is this needed**:
With https://github.com/gardener/gardener/pull/6018 and https://github.com/gardener/gardener/pull/6179 it is no longer possible to trigger control plane migration simply by changing the `shoot.Spec.SeedName` from the shoot `YAML` tab in the gardener dashboard. Instead operators that have the required permissions have to execute a rather complex curl query:
```
export NAMESPACE=my-namespace
export SHOOT_NAME=my-shoot
export SERVER=cluster-server-address
curl -k \
  --cert <path>/<to>/client.crt \
  --key <path>/<to>/client.key \
  -XPATCH \
  -H "Accept: application/json" \
  -H "Content-Type: application/merge-patch+json" \
  --data '{"spec":{"seedName":"<destination-seed>"}}  \
  'https://${SERVER}/apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/binding | jq -r ".spec.seedName"
```
Where `client.crt` and `client.key` need to be taken from the the kubeconfig that's used to talk to the garden apiserver if it uses certificate authentication.

Or:
```
export NAMESPACE=my-namespace
export SHOOT_NAME=my-shoot
export SERVER=cluster-server-address
curl -k \
  -XPATCH 
  -H "Accept: application/json" \
  -H "Content-Type: application/merge-patch+json" \
  -H "Authorization: Bearer <auth-token>" \
  --data '{"spec":{"seedName":"<destination-seed>"}}' \
  https://${SERVER}/apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/binding | jq -r ".spec.seedName"
```
If the kubeconfig uses a token to authenticate to the garden apiserver.

**Comment by petersutter** [comment]
hint: kube-client has to be extended similar to https://github.com/gardener/dashboard/blob/805b52e5939fd925274c663bec50d0cc1f9975b4/packages/kube-client/lib/resources/GardenerCore.js#L65-L67 or https://github.com/gardener/dashboard/blob/805b52e5939fd925274c663bec50d0cc1f9975b4/packages/kube-client/lib/resources/Core.js#L85-L87
