### ISSUE TITLE
wrong kubeconfig.yaml for the technical user

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#126]
I want create a cluster with the given kubeconfig.yaml for a technical user.
but the kubeconfig.yaml contains the wrong URL for the API server.

**Comment by vlerenc** [comment]
The URL should be (e.g. for Canary): https://gardener.garden.canary.k8s.ondemand.com (we manage the corresponding CNAME record automatically).

While on it, it makes sense to combine this with #125, which seems like a good idea.

**Comment by vlerenc** [comment]
It seems, that isn't working either, because the cert doesn't include https://gardener.garden...

**Comment by vlerenc** [comment]
@afritzler has patched the cert for an internal test landscape and it worked (after restarting the API servers). Kubify supports already (if you have a custom CNAME in addition to the landscape API domain):
```
additional_api_domains = [
  "*.garden.your.landscape",
]
```
