### ISSUE TITLE
Theming - favicon and logo broken 

### ISSUE THREAD

**Issue by Wieneo** [gardener/dashboard#1264]
**What happened**:
After upgrading the dashboard to version 1.60.0, using the official HELM chart, custom assets defined under "frontendConfig.assets" are ignored and the default Gardener assets are served. 

**What you expected to happen**:
Assets defined under "frontendConfig.assets" are served.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy Gardener Dashboard 1.59.0 with custom assets (works)
- Upgrade Dashboard to 1.60.0 (assets get replaced with defaults)

**Comment by holgerkoser** [comment]
I have fixed the issue in master https://github.com/gardener/dashboard/pull/1266 and it will be soon in the next release 1.61.0
