### ISSUE TITLE
Filter intentionally broken clusters

### ISSUE THREAD

**Issue by dguendisch** [gardener/dashboard#1269]
**What would you like to be added**:
It would be helpful to be able to annotate a shoot with e.g. `dashboard.gardener.cloud/ignore-issues` and the dashboard subsequently filtering away such clusters in the "All Projects" view (either when “Show only clusters with issues” is checked or a new filter item for this purpose would be added)

**Why is this needed**:
Customers regularly intentionally break clusters (e.g. because of chaos-testing, because of testing some knowingly broken machine images, ...). At the same time, operators proactively check the landscapes for clusters having issues (as shown in the "All Projects" view with filter “Show only clusters with issues” enabled), hence operators unnecessarily bother with intentionally broken clusters.

**Comment by petersutter** [comment]
We could re-use the `Hide no operator action required issues` filter and exclude shoots with `dashboard.gardener.cloud/ignore-issues` annotation from the list if checked
