### ISSUE TITLE
provide default settings for cluster creation

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#127]
It is possible to add a lot of secrets and infrastructures into one project - which is good.
But if I create a new cluster, e.g. for test purpose or dev, the first in the list is used.
...but almost alway it is not the cheapest one. 

It would be create if the project leader can mark a secret as **default** or **prefered**.
After this the secret is the default in the *cluster create dialog* if I'm setup a new one.

**Comment by freegroup** [comment]
## UI Proposal

<img width="1447" alt="bildschirmfoto 2018-08-16 um 13 09 19" src="https://user-images.githubusercontent.com/1155039/44205351-5cbdc480-a156-11e8-8877-111cf33a658a.png">

**Comment by grolu** [comment]
As mentioned in the linked ticket, we will improve usability and provide a way to sort cloud profiles as well as make the user explicitly chose an infrastructure / secret and not preselect a possible expensive one. However, there is nothing planned regarding (project specific) defaults.
