### ISSUE TITLE
Fetch secrets using labelSelector

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1284]
**What would you like to be added**:
Currently we list secrets https://github.com/gardener/dashboard/blob/96ca6590dfeabcb38296d6f7041b685991f56cc9/backend/lib/services/cloudProviderSecrets.js#L200 without using a labelSelector in order to fetch the cloud provider secrets.

Label `reference.gardener.cloud/secretbinding` could be a candidate for filtering out more relevant secrets (to be clarified).

**Why is this needed**:
As for each shoot there are several other unrelated secrets (kubeconfig, monitoring, ssh-key, ca-cluster..), the number of returned secrets can be quite high and thus unnecessary data needs to be processed and response times increase

**Comment by grolu** [comment]
This has already been addressed in this PR: https://github.com/gardener/dashboard/pull/1297
