### ISSUE TITLE
Add the `Target Cluster` to non-admin users

### ISSUE THREAD

**Issue by etiennnr** [gardener/dashboard#1298]
**What would you like to be added**:
As a Gardener operator, I frequently use the `target Cluster` feature of the dashboard since it's very quick and useful. However, while debugging with a customer today, I found out that this option is not available for non-admin users.

So, as a Gardener non-admin user, I want to have the `Target Cluster` feature available so that I can quickly and easily target my shoot cluster via gardenctl-v2

**Why is this needed**:
Would be very useful, mostly now that customers can disable the static token kubeconfig for their cluster. However, I would leave the `Target Control Plane` command to admin users only.

**Comment by petersutter** [comment]
Sure we can do that
/assign
