### ISSUE TITLE
Missing DNS provider when adding DNS secret in Gardener version > 1.54.0

### ISSUE THREAD

**Issue by kmadac** [gardener/dashboard#1305]
**What happened**:
There is no DNS providers available when we want to add new DNS Secret into the project.

**What you expected to happen**:
OpenStack designate should appear after click on + icon in DNS secret part

**How to reproduce it (as minimally and precisely as possible)**:
Install gardener version > v1.54 without any DNSProvider registration kind

**Anything else we need to know**:

**Environment**:
Gardener 1.54.1

If I understand it correctly, dashboard looks for DNSProvider records in controllerregistrations. But DNSProvider has been removed in gardener since v1.54.0 (https://github.com/gardener/gardener/releases/tag/v1.54.0). Is there a plan to implement the detection of DNS providers in different way? Or is there other way how to solve missing  DNSProvider in the current version (v1.61.0) of dashboard?

**Comment by grolu** [comment]
Yes, we are aware of this change and are currently discussing how to deal with it. We will let you know once we figured out how to move forward with DNS support
