### ISSUE TITLE
Dashboard HA Support

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#1315]
**What would you like to be added**:
Offer means to switch on and show HA per shoot

- [x]  #1373
- [x]  #223
- [ ]  #1391

**Comment by vlerenc** [comment]
@juergenschneider suggested a warning that downgrading (to none) or switching (from node to zone or vice versa) is not possible/supported.

**Comment by ashwani2k** [comment]
If this might help in defining the state diagram. https://github.com/gardener/gardener/issues/6529#issuecomment-1240195970 

Although a nice to have, I was wondering if it will be possible to identify a cluster via some icon to spot if a cluster is non-HA, singleZone-HA or multi-zone-HA. 
We can re-use the same notion to filter them based on the type of cluster both visually as well in the Projects cluster view.

**Comment by grolu** [comment]
To make the dashboard itself HA we need to solve the scalability issue: https://github.com/gardener/dashboard/issues/223

**Comment by grolu** [comment]
/close
Dashboard now supports to deploy and run multiple instances.
We do not support to define topologySpreadConstraints, an issue exists: https://github.com/gardener/dashboard/issues/1391
