### ISSUE TITLE
Monitoring Credentials location will change.

### ISSUE THREAD

**Issue by dkistner** [gardener/dashboard#135]
The location where the basic auth credentials for the monitoring stack are stored will change with PR [#271](https:,//github.com/gardener/gardener/pull/271) in the Gardener.

The dashboard have to read the credentials at this point in time out of a new secret called ``monitoring-ingress-basic-auth``, which is placed  in the Shoot namespace of the corresponding Seed cluster.

:warning: Depends on Gardener PR [#271](https:,//github.com/gardener/gardener/pull/271).

**Comment by plkokanov** [comment]
**Update**: the name of the new secret was changed to `monitoring-ingress-credentials`. 
However, do stay tuned for more updates until PR [#271](https://github.com/gardener/gardener/pull/271) gets merged.
