### ISSUE TITLE
Loading chunk <n> failed.

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#137]
When backend (or the frontend server in case of local development) goes down, the error 

> Loading chunk \<n\> failed

is shown. We also received a report from one of our users who also received this error while we have upgraded the dashboard to a newer version.

Either display a better error message or ask the user to reload the browser window.

How to reproduce (local development):
1. go to members section of a project
2. stop frontend server
3. Add user to project -> this will fail of course
4. Navigate to Administration page  -> this will show the above mentioned error

**Comment by grolu** [comment]
I've not seen this for a while and will be solved by backend refactoring anyway
