### ISSUE TITLE
Show project name in section "infrastructure"

### ISSUE THREAD

**Issue by s3ku** [gardener/dashboard#1375]
**What would you like to be added**:
The project name should also be shown next to "Provider / Region / Zone"

<img width="525" alt="image" src="https://user-images.githubusercontent.com/19580099/207558698-e040380f-423e-425b-9c58-2cdcd502bb12.png">

**Why is this needed**:
Helps investigating in which project the target cluster is located. This e.g. helps if quota issues arise to find the related project quicker.

**Comment by petersutter** [comment]
@grolu: @s3ku refers to the Openstack Project / Tenant Name. This information is within the respective infrastructure secret
