### ISSUE TITLE
Please drop `spec.provider.controlPlaneConfig.zone` field for OpenStack clusters 

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#1379]
**What would you like to be added**:
It seems, the `spec.provider.controlPlaneConfig.zone` field is no longer required (and contradicts HA in theory), at least I can create clusters without it just fine.

Please consider doing the same for GCP, once https://github.com/gardener/gardener-extension-provider-gcp/issues/541 is accepted/taken care of, please.

**Why is this needed**:
To reach full HA.

**Comment by ialidzhikov** [comment]
/close
in favor of https://github.com/gardener/dashboard/issues/1378
