### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/dashboard/blob/master/README.md"

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#143]
please add the **dashboard** logo on top of this page. a good example is https://github.com/gardener/gardenctl

![logo_gardener_dashboard 2x](https://user-images.githubusercontent.com/1155039/43255588-8e123d32-90ca-11e8-8c9f-60ad2540f311.png)

---
Page: [https://github.com/gardener/dashboard/blob/master/README.md](https://github.com/gardener/dashboard/blob/master/README.md)
don't remove the link to the page. It's required for the processor

**Comment by grolu** [comment]
Done
