### ISSUE TITLE
[master] Unify style of checkbox hint

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1584]
**What would you like to be added**:
On the create cluster page we have 3 different styles of checkbox hints

![2023-09-26_10-47-13](https://github.com/gardener/dashboard/assets/5526658/00135ae2-9238-4642-975d-656f8c0ea1b8)

**Why is this needed**:

**Comment by petersutter** [comment]
@grolu this was fixed meanwhile, right?

**Comment by grolu** [comment]
/close
done
