### ISSUE TITLE
Dashboard Link w/o Dashboard Addon

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#160]
I have created a cluster without Kubernetes dashboard (less attack surface), but the Gardener Dashboard (still) shows a Kubernetes dashboard link in the cluster details:
![screen shot 2018-08-08 at 15 53 37](https://user-images.githubusercontent.com/4974203/43841378-56094b70-9b23-11e8-8b46-953562a542da.png)

**Comment by grolu** [comment]
We currently always show the dashboard link when we are able to get a cluster URL from the cluster kubeconfig (we generate the url by adding /ui). There is no logic in place to check if there is actually a dashboard running in a specific cluster. To determine, if there is actually a dashboard running, we would need to look for the kubernetes-dashboard service when fetching the shoot info, right? @petersutter @holgerkoser

**Comment by petersutter** [comment]
..or we could check the shoot spec for the dashboard addon?

**Comment by vlerenc** [comment]
Yes, that's what I meant. I was too lazy painting red circles around the addon and the monitoring section.

**Comment by holgerkoser** [comment]
From my point of view in general the referrer is not responsible for the availability or the existence of the target. I don't see a problem with showing a link which will result in 404. This indicates that the dashboard is not deployed. Anyway the url /ui redirect is removed (https://github.com/kubernetes/kubernetes/pull/53766).

**Comment by petersutter** [comment]
regarding /ui:
we already have the path configurable but we should consider removing the default, which points to /ui: https://github.com/gardener/dashboard/blob/master/frontend/src/store/modules/shoots.js#L165-L166
