### ISSUE TITLE
How To Link broken

### ISSUE THREAD

**Issue by bkrannich** [gardener/dashboard#162]
"?" --> "How To" leads to https://github.wdf.sap.corp/pages/kubernetes/gardener/howtos which is a 404.

Is this now rather "?" --> "Tutorials" pointing to https://github.wdf.sap.corp/pages/kubernetes/gardener/developer/topic/ ?

Thanks,
Bernd

**Comment by petersutter** [comment]
Hi Bernd,

this is a configuration issue of our internal deployment. I have created an issue in the respective landscape-setup repository, hence I will close this issue.

Best regards,
Peter
