### ISSUE TITLE
Please, do not show hidden cluster ticket comments

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#1640]
**What would you like to be added**:
When tickets are shown for a cluster, please do not show hidden comments. There were (probably always) good reasons to hide a comment in GitHub, so they shouldn't be shown in the Dashboard either.

**Why is this needed**:
Show only appropriate content. Respect decision made for GitHub also in Dashboard.

**Comment by holgerkoser** [comment]
The information that a comment is hidden seems not to be available in the github API:
```json
{
  "url": ".../issues/comments/12345678",
  "html_url": ".../issues/815#issuecomment-12345678",
  "issue_url": ".../issues/815",
  "id": 12345678,
  "node_id": "ABCDEF...",
  "user": {
    ...
  },
  "created_at": "2023-12-08T13:23:31Z",
  "updated_at": "2023-12-08T13:23:47Z",
  "author_association": "MEMBER",
  "body": "The comment body",
  "reactions": {
    "url": ".../issues/comments/12345678/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "performed_via_github_app": null
}
```

**Comment by vlerenc** [comment]
Not via the ReST API, it isn't. I manipulate this and some other settings via graphQL. I do not know why some features are available only through the graphQL API.

**Comment by vlerenc** [comment]
Thx!
