### ISSUE TITLE
missing warning before upgrade/update my cluster

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#171]
There is no warning or something similar in the dialog. Just select the new version and press ok.
In almost every case, the user didn't have in mind to test the software after a migration.

<img width="542" alt="bildschirmfoto 2018-08-14 um 16 03 47" src="https://user-images.githubusercontent.com/1155039/44096487-a879c2c4-9fdb-11e8-921a-6659444a468a.png">

**We should explain the risks to the user before the update is performed.**

Something like this could help to bring the risk into mind

>   Please make sure that your software is still working properly after the upgrade. Of course, you may 
>   have used functionality of a current version that behaves differently in the next version. 
>   Automatic tests are a good tool to prepare and protect your software for such cases.
>   Don't do this operation on a productive system without test them before.

You should avoid blaming the gardener for any mistakes. And explain the risk for such danger operation is a good choice.

**Comment by grolu** [comment]
There is a warning before you **upgrade** your cluster, you even need to confirm by typing the cluster name:
<img width="496" alt="screen shot 2018-08-14 at 4 07 16 pm" src="https://user-images.githubusercontent.com/35373687/44096713-393b75dc-9fdc-11e8-97c5-af1c754e7bc0.png">

However, for **updates** we do not show a warning. Usually, patches are applied during maintenance. If a user decides to uncheck this option and patch manually, we still don't see the requirement to show a warning as updating to a newer patch version should never break anything inside the cluster.

**Comment by freegroup** [comment]
Maybe a user has a good reason to disable the feature for the automatic patch installation.
Especially for compatibility reasons and a well defined CI/CD pipeline with dev/staging/live testing.
Especially in such cases, one should point out the risks to the user

A good example is the https://www.youtube.com/watch?v=OUYTNywPk-s . 
Complete outage of the Monzo bank. Reason installing a patch version of etcd.

**Comment by grolu** [comment]
We should rename the button to update / upgrade to make it cleat that tapping the button does not only close the window...
In addition, we could always warn the user before updating a **productive** cluster. This ways, we would not change UI flow for non productive clusters. However, I don't want to include too much help / warning text on the upgrade dialog. I expect that an administrator knows what can happen when pressing that button
:radio_button: :boom:

**Comment by vlerenc** [comment]
You may be interested in the overall epic: https://github.wdf.sap.corp/kubernetes/kube-backlog/issues/19 when discussing the next steps.

**Comment by freegroup** [comment]
+1 for **prod** cluster solution

**Comment by grolu** [comment]
@freegroup In our UI sync we agreed to change the color to orange / warning color for all cases (update/upgrade). In addition, we will shot the upgrade path, e.g. 1.11.1 -> 1.11.2 in the dropdown list.
However, we will **not** show the confirmation input field for patch updates. The above changes should give enough feedback to the user to not accidentally perform an update.

**Comment by grolu** [comment]
In addition to the things mentioned above, the user now has to explicitly select a version to upgrade to on the dialog, there is no version pre-selected.
The improvements will be included in the next release.
