### ISSUE TITLE
New Shoot status should be reflected

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#181]
The `.status.lastOperation.state` can have one of the `Processing|Succeeded|Error|Failed` values. Since the last version Gardener sets `.status.lastOperation.state=Aborted` for all Shoots that were `Processing` during its start.
The dashboard does not know about this new state and shows the green checkbox as if the state would be `Succeeded`.

**Comment by petersutter** [comment]
should it have the error color? 🤔
