### ISSUE TITLE
Allow immediate maintenance of a Shoot

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#195]
A shoot maintenance operation can now be triggered immediately by annotating the Shoot with `shoot.garden.sapcloud.io/operation=maintain` (even outside the maintenance time window).

We should add this functionality to the dashboard.

**Comment by petersutter** [comment]
https://github.com/gardener/gardener/commit/1e5cc01e1e6e2433dea68adab556a82d82bead06

/cc @rfranzke

**Comment by vlerenc** [comment]
+1
