### ISSUE TITLE
Do no longer create Terraformer ClusterRoleBinding

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#20]
The dashboard does no longer need to create the Terraformer `ClusterRoleBinding` when creating a project/namespace: https://github.com/gardener/dashboard/blob/4a059ce697dec27d04cb77a6b145ad8b70427171/backend/lib/kubernetes/Client.js#L455-L477

The Terraform jobs are running in the Seed clusters and the Gardener creates the required `(Cluster)RoleBinding`s itself.

**Comment by petersutter** [comment]
fixed with #32
