### ISSUE TITLE
Redesign Create Cluster Dialog

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#208]
The Create Cluster Dialog needs a complete overhaul to improve usability. More options have been added to the different tabs of the dialog and the usage is not straight forward anymore (e.g. changing infrastructure on tab#1 reverts options on tab#2 etc.). In addition, we need to integrate more features, e.g. a shoot yaml editor as last step before creation. Therefore we need to completely redesign the create cluster dialog:
Current planned activities:
- Get rid of the dialog, rather use a a dedicated page for the creation prcoess
- Change to a creation wizard mode, advantages:   
  - Make evaluation and default value selection less complex
  - Avoid hidden value resets on other tabs (as described above)
  - We can have a dedicated final page with the generated (editable) yaml (see also  #34)
- Do not pre-select all values, some values should be selected explicitly (e.g. infrastructure)

Maybe this issue (together with #207) also helps solving #127 (reduce costs)

**Comment by vlerenc** [comment]
Thank you @grolu. It will be hard to improve the cluster creation dialog, because people are generally very satisfied with it and we get extremely good feedback. Still, you mention valid points. I guess, I am basically saying, it will be tough to improve in comparison to what we already have. ;-)

Solutions for #207/#127 would indeed be nice. As an idea, while you speak about defaults, maybe different "cluster templates" could make sense, too.

**Comment by freegroup** [comment]
I like the dialog as well. 

One big improvement could be to restore the last settings for a new cluster creation.
In this case, the last settings are applied to the new cluster. e.g. type of Infra, NodeTypes,...

I don'T like a wizard. The very first draft was a wizard and the feedback was not so good.
The problem with a wizard is, that you must run to the end.....even if you know that everything
 fits well.

**Comment by freegroup** [comment]
If you add another button "Next", you show the user that there are still other setting possibilities and still you can create the cluster without further action.

Now you didn't have any **hidden** settings.

<img width="1448" alt="bildschirmfoto 2018-10-15 um 10 36 14" src="https://user-images.githubusercontent.com/1155039/46939366-64222100-d066-11e8-8918-607ecb5d99dd.png">

**Comment by grolu** [comment]
We will take all comments into consideration. There is no final concept yet and we certainly do not want to make cluster creation more complicated for our users. However, we expect that we can ask our users to think twice before creating a cluster, considering costs, expected workload, etc. (which is, by the way, not an every day task - if so, this should be automated...) 
We will give an update once we have a first concept.
