### ISSUE TITLE
Enforce Array Syntax for Lodash `path` Parameter

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#2099]
**What would you like to be added**:

Lodash's `path` parameter should always use array syntax. This approach is more secure against injection attacks, reduces the risk of accidental errors, and improves performance as it avoids the unnecessary `stringToPath` conversion.

_Preferred:_
```js
const value = get(obj, [key])
```

_Avoid:_
```js
const value = get(obj, key)
```

**Why is this needed**:
- **Security**: Prevents potential injection attacks or errors from dynamically generated string paths.
- **Performance**: Using array syntax skips the `stringToPath` conversion, as detailed in the [Lodash source code](https://github.com/lodash/lodash/blob/main/src/.internal/castPath.ts#L12-L17).

This rule should be enforced across the codebase to maintain consistency and leverage these benefits.

**Comment by grolu** [comment]
/close
completed with #2174
