### ISSUE TITLE
Include aware for Kubernetes release notes in upgrade dialog

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#210]
We should add awareness for reading the Kubernetes release notes when upgrading a cluster.

Please either link to
- https://github.com/kubernetes/kubernetes/releases
or e.g.
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#v1120

**Comment by grolu** [comment]
We will add it to the update cluster dialog like this:

Kubernetes Release Notes on GitHub: https://github.com/kubernetes/kubernetes/releases
