### ISSUE TITLE
Different UI elements for status display

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#211]
The Dashboard uses different UI elements for  the same kind of information display
This type of display should be aligned

## current
<img width="706" alt="reconcile_current" src="https://user-images.githubusercontent.com/1155039/46935197-c70dbb00-d05a-11e8-8639-017a26c96715.png">

## proposal
<img width="717" alt="reconcile_" src="https://user-images.githubusercontent.com/1155039/46935212-cd9c3280-d05a-11e8-84e3-15423926560b.png">

**Comment by grolu** [comment]
We plan to do a complete overhaul of the cluster details dialog, see #139

**Comment by grolu** [comment]
We currently do not plan to plan to further redesign the conditions.
