### ISSUE TITLE
Different Icons for dashboard and kubeconfig

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#212]
For the kubeconfig and the dashboard different Icons are in place.

To make it easy for the user, the identical icons for the same element should always be used.

<img width="1015" alt="bildschirmfoto 2018-10-15 um 09 21 50" src="https://user-images.githubusercontent.com/1155039/46935632-04bf1380-d05c-11e8-8bc4-8a4a94297bd5.png">

**Comment by grolu** [comment]
We plan to merge dialogs on the cluster list, so this issue will be resolved with this ticket: #148
