### ISSUE TITLE
wrong placed "hibernate" section

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#213]
The current position of the **hibernate** information  of the cluster breaks the UI.

<img width="1112" alt="bildschirmfoto 2018-10-15 um 09 26 14" src="https://user-images.githubusercontent.com/1155039/46937070-96308480-d060-11e8-9b07-e0499d4b495e.png">

## The Detail page of the cluster is split into different sections

- Detail
- Status
- Access

<img width="1022" alt="bildschirmfoto 2018-10-15 um 09 50 51" src="https://user-images.githubusercontent.com/1155039/46936855-fd9a0480-d05f-11e8-8109-7a2c89f3e3d7.png">

The **hibernate** information is arranged in the detail area although it is a status information.

## Proposal
I suggest to rearange the UI and place the **hibernate** in the Status Section of the Cluster. Additional I changed the title of the status section, the icon of the hibernate partial and the Reconcile partial. This makes the overview look less restless and clearer.

<img width="1195" alt="bildschirmfoto 2018-10-15 um 10 04 18" src="https://user-images.githubusercontent.com/1155039/46937519-caf10b80-d061-11e8-8aff-21b0591290d4.png">

I think, that the proposal is more alligned to the current arrangement of th e UI elements

**Comment by petersutter** [comment]
yes I agree that it should not be on the details card.
In the future we will also have the ability to configure the hibernation schedule and show the rest of the "missing" information, e.g. the stuff that is shown on the cluster creation dialog on the maintenance tab. Maybe we want to combine those into one (cluster) lifecycle card/section or similar

**Comment by grolu** [comment]
We plan to do a complete overhaul of the cluster details dialog, see #139

We will **not** do intermediate changes, as we work on other topics with higher prio.
