### ISSUE TITLE
Broken Label/Information pattern

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#214]
Almost all display elements use the same layout, the label at the top and the value at the bottom.
The **kubernetes version** breaks this rule.

<img width="1067" alt="bildschirmfoto 2018-10-15 um 10 16 58" src="https://user-images.githubusercontent.com/1155039/46938752-d4c83e00-d064-11e8-9c99-38670f48a3b8.png">

## Proposal

<img width="1076" alt="bildschirmfoto 2018-10-15 um 10 21 18" src="https://user-images.githubusercontent.com/1155039/46938720-c0844100-d064-11e8-8ef7-d8f33c640c77.png">

**Comment by grolu** [comment]
We plan to do a complete overhaul of the cluster details dialog, see #139
