### ISSUE TITLE
YAML Syntax checker / Indicator didn't work

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#216]
the syntax checker seems not to work. Even if I enter crap YAML, the syntax checker is always *Green* and signals me that everything is fine.

<img width="1113" alt="bildschirmfoto 2018-10-15 um 10 50 17" src="https://user-images.githubusercontent.com/1155039/46940174-61283000-d068-11e8-8043-8655076a81b3.png">

**Comment by grolu** [comment]
This "button" is not a syntax checker but gives you feedback, if the resource can be saved without conflicts or if it has changed in the meantime. There is a tooltip which explains the purpose of the icon. At the moment, we do not plan to add a syntax checker.
