### ISSUE TITLE
Search in YAML not working properly for `Shoot`s in `garden` namespace

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#2166]
**What happened**:
When using CTRL + F to search for something at the bottom of the YAML there is no search result for `Shoot`s in the `garden` namespace.

The new search and replace ui element of codemirror 6 is not displayed in this case
![Image](https://github.com/user-attachments/assets/d5bea4fe-59bc-405a-9c4f-2c0b2749f606)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by dguendisch** [comment]
I anyway prefer the browser's native search UI, the strange thing: since either some Chrome version or some dashboard version, it also no longer works (as in: doesn't find the search string) when using Cmd+F with the native search UI (unless I'm explicitly scrolling to the section that contains the searched string)

**Comment by grolu** [comment]
>The new search and replace ui element of codemirror 6 is not displayed in this case

Probably because the shoot is readonly. We need to check if we can change the behavior

>since either some Chrome/Safari version or some dashboard version, it also no longer works (as in: doesn't find the search string) when using Cmd+F with the native search UI 

Probably this stopped working with cm6.

I will have a look

**Comment by grolu** [comment]
There seems to be an issue with CM6 search in readonly documents: https://github.com/codemirror/dev/issues/1469

Regarding using native browser search: There are ways to achieve this by forcing CodeMirror to render the whole document. While this was kind of supported / tolerated in CM5, this is explicitly not supported in newer versions to prevent performance issues. We could hack around this but I don't think this is a good idea. @dguendisch if the CodeMirror internal search works for all clusters (including readonly ones) - would this be ok for you? Or should we try to support native search anyway?

**Comment by dguendisch** [comment]
> if the CodeMirror internal search works for all clusters (including readonly ones) - would this be ok for you?

Yes, sure 👍
