### ISSUE TITLE
Stay/Leave button in YAML editor not clear 

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#217]
The buttons in the YAML editor are not clear for me. 
I must always think about what happens....this is different for the commonly used dialog in Chrome or IE (see below). The text on the button itself makes it totally clear
what happens.

## YAML Editor
<img width="555" alt="bildschirmfoto 2018-10-15 um 11 06 55" src="https://user-images.githubusercontent.com/1155039/46941854-596a8a80-d06c-11e8-86b7-23727f085d16.png">

## Commonly used dialogs

<img width="541" alt="bildschirmfoto 2018-10-15 um 11 21 03" src="https://user-images.githubusercontent.com/1155039/46941897-7010e180-d06c-11e8-895f-fbe02c92c6f4.png">

<img width="568" alt="bildschirmfoto 2018-10-15 um 11 16 01" src="https://user-images.githubusercontent.com/1155039/46941818-4061d980-d06c-11e8-8136-00577a9d445b.png">

<img width="553" alt="bildschirmfoto 2018-10-15 um 11 16 32" src="https://user-images.githubusercontent.com/1155039/46941833-49eb4180-d06c-11e8-9cb2-c8273b51773c.png">

<img width="652" alt="bildschirmfoto 2018-10-15 um 11 16 21" src="https://user-images.githubusercontent.com/1155039/46941822-43f56080-d06c-11e8-8cbf-df4e863a10e0.png">

**Comment by petersutter** [comment]
there are also counterexamples.. like
<img width="421" alt="screenshot 2018-10-16 at 18 02 49" src="https://user-images.githubusercontent.com/5526658/47030404-f82ae000-d16d-11e8-8a6a-cfa353ae1bf8.png">

**Comment by freegroup** [comment]
your sample is much better. I like the "Cancel" option - which is more clear to me.

the words "Stay" or "Leave" force me to think more about it. "Cancel" is familiar and you know immediately that the last operation should be stopped...whatever I wanted to do. +1

**Comment by grolu** [comment]
Other examples (like ours):
![image (1).png](https://images.zenhubusercontent.com/5a9e461b4b5806bc2bc98cf3/0be66369-abee-4939-9f0d-4063beddd685)

![image.png](https://images.zenhubusercontent.com/5a9e461b4b5806bc2bc98cf3/4a2f9073-768c-4eb5-96be-b94aa4267468)

Personally, I do not feel that we need improvement here. To me, it is very clear what "leave" or "stay" means. Moreover, if we want to be 100% correct, "Leave this Page" would be wrong anyway as we have a single page application 😉

**Comment by freegroup** [comment]
"single page" is the technical implementation....not what the users see. But anyhow - we have discussed this in our team and we have seen this as an issue.

**Comment by grolu** [comment]
We will change the dialog in the next release to look like this:

<img width="354" alt="screen shot 2018-10-17 at 15 37 09" src="https://user-images.githubusercontent.com/35373687/47090190-ad1ed480-d222-11e8-8a18-5eb3bbd3bbd3.png">
