### ISSUE TITLE
Scheduled Hibernation

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#227]
As an owner / administrator of a cluster I want to have the option to define a schedule, that automatically hibernated and wakes up a cluster depending on when it is needed. This is especially useful for development / test scenarios.
The configuration UI should be part of the create cluster dialog as well as on the shoot details page.

We also want to show an alert banner on the detail page of clusters that are non productive but have no hibernation schedule. This warning can be suppressed by setting an annotation to the shoot spec. Also, we should offer a filtered view of all non-prod clusters without a schedule or ignore flag.

This item depends on: https://github.com/gardener/gardener/issues/348

**Comment by petersutter** [comment]
gardener PR: https://github.com/gardener/gardener/pull/507
