### ISSUE TITLE
Create/View/Modify Shoot Cluster Spec

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#23]
# Story
- As user I want to see my shoot cluster spec in a readable form (not only the yaml), so that I know what I have configured for my cluster.
- As user I want to modify my shoot cluster spec, so that I can update it rather than having to create a new shoot cluster and move my workload.

# Motivation
With the advent of the automated cluster updates and the machine controller manager, we will be able to change an existing shoot cluster, so let's expose this functionality.

# Acceptance Criteria
- [ ] User can change the following shoot cluster spec settings
  - [x] Kubernetes version
  - [x] Referenced Secret (show warning!)
  - [x] Purpose
  - [ ] Cluster Lifetime (see Gardener acceptance criteria [here](https://github.com/gardener/gardener/issues/81) on cluster lifetime extensions)
  - [x] Worker pools (in general: adding new, changing or deleting existing ones)
    - [x] Name
    - [x] Machine types and disk
    - [x] Min/Max
  - [x] Addons

## Not Possible
- Name, infrastructure and region (in general)

# Implementation Proposal
Replace cluster creation dialog with a page similar to cluster details. That page can then be used to create a cluster, see its configuration and change it. Also make the yaml view editable, so that users can e.g. tweak the network settings (expert mode) and more directly in yaml (and the dashboard doesn't need to implement these complex scenarios).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?

**Comment by vlerenc** [comment]
Can we close this one as well now that #208 is also open?

**Comment by grolu** [comment]
we have not completed all of the things above. There are still some things missing, e.g. cluster purpose and referenced secret.
Of course we can discuss if we want to have this configurable via the UI or just point the user to the yaml editor.
As for add-ons and cluster lifetime I think there are currently no plans to offer edit possibility in the UI (I had a discussion with @adracus about add-ons and we agreed that edit functionality makes not much sense as this add-on concept is more or less deprecated)
