### ISSUE TITLE
Cluster Creation & autoScalerMin=autoScalerMax=0

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#230]
currently the dashboard allows to create a cluster where all worker pools can have autoScalerMin=autoScalerMax=0.

This behavior will change with gardener/gardener#471:
- we should check that there is at least one worker pool that has autoScalerMin=autoScalerMax>0
- only take spec.hibernation.enabled into consideration if cluster is hibernated and [remove](https://github.com/gardener/dashboard/blob/efe3d58cadddd21940b62fdeee4d316cdf94ceba/frontend/src/utils/index.js#L257-L267) the fallback (autoScalerMin=autoScalerMax=0)

**Comment by grolu** [comment]
Related #279
