### ISSUE TITLE
Allow user to specify Service/Pod CIRD when creating a cluster

### ISSUE THREAD

**Issue by afritzler** [gardener/dashboard#236]
We have a user request, where they want to specify the service/pod CIRD ranges from the dashboard when creating a cluster.

**Comment by petersutter** [comment]
Currently this only possible by creating a robot user / service account in the members section and using that to create a shoot resource.

Will close this ticket in favor of #208

**Comment by afritzler** [comment]
Yes the user is aware of the manual shoot creation. Is this considered in your redesign?

**Comment by petersutter** [comment]
Currently we have no plans to add such input fields to the cluster creation dialog anytime soon, except there is a strong demand for it.

However, we plan to add a yaml editor on the cluster creation dialog where the user can tweak the spec.
