### ISSUE TITLE
Cluster overview isn't refreshed if user creates a new one

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#249]
I miss the new created cluster/shoot in the overview page after 
the cluster has been created. The cluster is part of the lister after page refresh.

![missing_cluster_after_create](https://user-images.githubusercontent.com/1155039/48548726-f6b81900-e8cd-11e8-99de-f59e3614e4b3.gif)

**Comment by grolu** [comment]
We are aware of this issue and already investigating. Thank you for opening an issue for this.

**Comment by grolu** [comment]
We did no experience this for a while now. Seems to be fixed.
