### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#25]
In order for the landscape deployment, the Gardener packages itself as Helm chart, see https://github.com/gardener/gardener/tree/master/charts. When this is stable, it would be great to also have a Helm chart for the dashboard (one or two, depending on whether we should package dex separately), so that a landscape can be set up using the same means.

**Comment by holgerkoser** [comment]
Creted separate charts for [dashboard](https://github.com/gardener/dashboard/tree/master/charts/gardener-dashboard) and [identity](https://github.com/gardener/dashboard/tree/master/charts/identity). Integration into landscape setup needs to be done.

**Comment by rushins** [comment]
i didn't find the gardener helm when i do "helm search gardener" i dont see anything available ? does gardener is official on catalog >. Can someone point me how to install gardener with helm chart as there is no straightforward documentation how to install..

**Comment by Diaphteiros** [comment]
@rushins Gardener is not in the official helm repo. You can find an example use of the Gardener helm chart in the [landscape-setup](https://github.com/gardener/landscape-setup). Check the `components/gardener` folder in there or have a look at the complete [landscape-setup-template](https://github.com/gardener/landscape-setup-template) (this is slightly outdated right now, a pull request for the newest Gardener version is in the making).

**Comment by vlerenc** [comment]
Still, the question by @rushins is valid. Why isn't it? Could you please discuss that internally and with the Gardener and Dashboard code owners?
