### ISSUE TITLE
Adapt to new shoot condition states

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#254]
The current shoot conditions reflect the most recently observed state of a shoot. Users often misinterpret the status and get the impression that their cluster is somewhat broken. A good example for this is e.g., when the cluster-autoscaler decides to scale up. It increases the .spec.replicas field of the MachineDeployment, however, the EveryNodeReady condition shows False with the message Not enough nodes (x/y) are registered to the cluster.
To overcome this issues, Gardener plans to implement some changes, to which the dashboard needs to be adapted.

1. There will be a  new state Progressing (next to True, False, Unknown) in a condition's spec. The dashboard will show this state same as healthy (no error / warning color), the Progressing state should only be visible in the tooltip / popup.

2. Operators can filter the all shoots list by shoots with issues. This is done by selecting shoots with the unhealthy label:
```
shoot.garden.sapcloud.io/unhealthy=true
```
We need to change the selector to ignore the value, as it will include the progressing state as value, if no other condition is False. We can then offer another (client-side) filter in the all shoots with issues list to show progressing shoots (default=false)

This issue depends on: https://github.com/gardener/gardener/issues/545

**Comment by rfranzke** [comment]
FYI: gardener/gardener#552 is merged. It will be released with the next version (0.14.0). The release is planned for this week.

**Comment by grolu** [comment]
I had a look at our implementation and it looks like we do not need to align our releases. The Dashboard will treat the new "Progressing" state as "True", so there will not be an error shown for the Progressing state. We will have a closer look on how to visualize the Progressing state properly after you released your code. Current Idea: Show "Progressing" in popup title

**Comment by vlerenc** [comment]
That's good news. When you start working on visualising `progressing`, I guess some visual clue (non-alarming) would be still helpful to us (Gardener/Ops). Not sure whether it's another neutral colour or some icon overlay.

In general, we should avoid any alarming indicators unless the cluster is rated unhealthy (be it conditions or last operation). We do not hide stuff, but if things are in progress, it's just that and in the past we have alarmed the people more often than was good for them and our rep. ;-)
