### ISSUE TITLE
Sort clusters by version

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/dashboard#263]
The recent [K8s Security Announcement](https://groups.google.com/forum/#!topic/kubernetes-announce/GVllWCg6L88) made it necessary to sort the long list of clusters by version to identify the clusters which have a vulnerable version and need to be updated or upgraded. Sorting by version is currently possible in the Gardener Dashboard but not in the desired way. An alternative would be to enter a version in the search field and get a filtered list.

**Comment by grolu** [comment]
I already discussed this with @holgerkoser  and we decided to change the sorting behavior (basically we will no longer rank clusters that can be updated at the top but will sort only by version value.
The second option is also a valid use case. Currently, we search only on the `name` column. However, it makes sense to also allow search on other columns. I will have a look at it.
