### ISSUE TITLE
Dashboard is very slow and unresponsive when listing all clusters

### ISSUE THREAD

**Issue by StenlyTU** [gardener/dashboard#266]
**Dashboard is very slow and unresponsive when listing all clusters.**
The problem is observed only on Canary. It takes ~18s(measured from 10 attemps) to load all clusters regarless of their state. Clicking on the search panel after that is still very slow. Sometimes the Dashboard freezes at all, even receiving "something went wrong". 
![1](https://user-images.githubusercontent.com/43163861/49855186-18d18800-fdf5-11e8-8b9d-c08a66b51035.png)
**How to Reproduce:**
1. Log into Canary Landscape Dashboard
2. Select ALL PROJECTS
3. Unselect ''Show only clusters with issues'
4. Click on search panel

**Comment by grolu** [comment]
Hi,
this is a known issue related to client side rendering of the huge cluster table. I have some Ideas on how to improve this, but did not find the time to do so yet. I will keep this issue open and keep you updated.
