### ISSUE TITLE
Advertise New Kubernetes Minor and Patch Versions

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#27]
# Story
- As user I want to be informed when I can update/upgrade my Kubernetes cluster, so that I can stay on the latest version and benefit from the latest features and fixes.

# Motivation
We as provider want to motivate our users to run the latest Kubernetes version, so that we have less issues with the clusters, offer the latest features and can faster drop support for older Kubernetes versions.

# Acceptance Criteria
- [x] Dashboard shows that an update (higher patch version)/upgrade (higher minor version) is available for a cluster (in list and detail view)
- [x] User can easily patch a cluster (with the click of a button and an additional confirmation)
- [x] User can easily upgrade a cluster (with the click of a button and a warning about possible incompatibilities and an additional confirmation)

# Definition of Done
- [x] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [x] Integration Tests are provided: Have you written automated integration tests?
- [x] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?

**Comment by grolu** [comment]
The implementation is done. However, we got some feedback that we should discuss in an upcoming UI sync:
- the texts need to be reviewed. Especially the upgrade warning text (which is based on what is stated in the Kubernetes docu) should be changed
- We currently show all available versions that a user can upgrade to, however only allow upgrading more than one minor version at a time. If the user selects an invalid version, we show an appropriate message and disable the upgrade action. Question is, if this is the desired behavior or if we should make invalid versions non selectable. Doing so, we would loose the ability to show an error message though.
