### ISSUE TITLE
Enable Alicloud 

### ISSUE THREAD

**Issue by jia-jerry** [gardener/dashboard#277]
1. Enable user to add shoot Alicloud cluster
2. For private cloud(currently for Alicloud), add a special flag when start Dashboard. 
- Just a suggestion. The start option name is **exclusive-provider**, the value coudl be **alicloud**
- If the value is specified for the option **exclusive-provider** and it is set alicloud, in the dashboard, only Alicloud cluster can be choosed to create.

**Comment by holgerkoser** [comment]
If you only have one cloud provider for Alicloud it should behave exactly like you propose. Only Alicloud shoots can be created. I don't think we need a flag for this. Or am I missing something here?

**Comment by jia-jerry** [comment]
I think so.  I will close it after it is verified in dev landscape. Thanks @holgerkoser
