### ISSUE TITLE
Hibernate/Wake-Up Clusters

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#28]
# Story
- As user/operator I want to hibernate clusters, so that I can save costs when I don't need the clusters anymore/temporarily.

# Motivation
See gardener/gardener#50 in which the required Gardener functionality was implemented.

# Acceptance Criteria
- [ ] Cluster can be scaled down to 0 machines across all pools and up again

# Implementation Proposal
We can either do nothing (basically only do #23, which we like to do anyways) and leave it to the user to find out that by scaling down all pools manually he can effectively hibernate a cluster or we can offer some convenience function in the dashboard that does that across all pools, clearly labeled "Hibernate". The reverse operation, "Wake-Up", is harder, but maybe the former pool sizes could be written as annotations into the shoot resource by the dashboard, in which case "Wake-Up" would know how to scale up again.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by petersutter** [comment]
prerequisite: gardener/gardener#191

**Comment by albra66** [comment]
Just as an idea: What about giving an operator the possibility to hibernate certain clusters based on time, eg. hibernate all dev-clusters at 10.00 pm and wake them up the following day at 07.00am.

**Comment by petersutter** [comment]
*Brainstorming* 
We could add something like that to the cluster creation dialog which is enabled by default for evaluation- and development-purpose clusters and the gardener controller is taking care for the auto-sleep

**Comment by petersutter** [comment]
Allow auto-hibernation/wake-up configuration in Shoot specification - https://github.com/gardener/gardener/issues/348
