### ISSUE TITLE
Allow login with Token / Kubeconfig

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#285]
Currently, an OIDC provider is required to login to the dashboard. A first step to allow different login methods is to provide an input field to access the dashboard with an access token. Also, we need to remove checks in the frontend that evaluate if the token is a valid Kubernetes token which it is in our current setup, however this is not an requirement and not always the case. The backend acts as proxy and uses the provided token to access the APIServer where the actual validation is done. However, we need to pay attention when we use the system account (admin) to make calls.

@holgerkoser please correct and complement the text above

**Comment by praveendhac** [comment]
Kubernetes by default provides `token` based authentication
https://github.com/kubernetes/dashboard/wiki/Access-control

We have 2 options to access dashboard
- kubeconfig
- basic
kubernetes-dashboard in the Shoot cluster is not associated with any basic configuration file, it is associated to service-account and authenticating using `kubeconfig` doesn't work so there is no way to access dashboard after the default SKIP option is removed.
