### ISSUE TITLE
Maintenance Time Window

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#29]
# Story
- As user I want maintenance to occur only in specified time windows, so that the impact is minimal on my business/development.
- As provider I want cluster maintenance to occur not all at once, so that I don't overload the infrastructures.

# Acceptance Criteria
- [ ] Start time of maintenance can be defined per shoot cluster (maybe we need to generate start and end time at the moment, but the goal is to define only the start time in the UI); during shoot cluster creation we shall randomly create a maintenance start time proposal ~during the target region's nighttime (like AWS does)~ (for now GMT is OK)
  - [ ] User can specify whether Kubernetes patch version updates should be applied automatically or not during maintenance procedure, otherwise only OS updates are scheduled for that time frame

# Resources
Prerequisite is gardener/gardener#84 that introduces maintenance time windows into the shoot cluster resources.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?
#

**Comment by petersutter** [comment]
comitted with https://github.com/gardener/dashboard/commit/5a71b4fd640c9065ec8bc29f05f9c91250bc85b8

**Comment by petersutter** [comment]
what min maintenance time window should we enforce? 30min? 1 hour?

**Comment by rfranzke** [comment]
minimum is 30 minutes, maximum 6 hours

**Comment by vlerenc** [comment]
As discussed, let's use an hour as the time window (the controller will act certainly faster), but let's not show the end time (time window) in the UI to not give the wrong impression that we would complete the update within that time window (show only the start time). The time window is merely and technical vehicle for the controller to act within.

**Comment by vlerenc** [comment]
Thank you!

Question: Why can I delete the maintenance start time, when it's rightfully required?![Screen Shot 2018-03-20 at 05.30.49.png](https://images.zenhubusercontent.com/5a57377f4b5806bc2bc254ee/30fa8d26-4bd3-4a25-8109-86a79c5ae911)

**Comment by grolu** [comment]
Good point. This can be solved by setting the text field to required which will also display an asterisk next to the label. I will do this for all required input components on the create cluster dialog.

**Comment by vlerenc** [comment]
Thanks!
