### ISSUE TITLE
Add worker group information to "Cluster Details"

### ISSUE THREAD

**Issue by ddegraf** [gardener/dashboard#3]
Hi,
I've noticed that once you've created a cluster, you cannot find any information about the worker you've defined (apart from looking into the yaml config). For me it would be interesting to see the VM types (and maybe autoscaler and disk information) of my worker groups.

Any thoughts on that?

Best regards
Daniel

**Comment by vlerenc** [comment]
At the latest, this will become possible when we expose cluster updates to the users: #23.
