### ISSUE TITLE
Restrict User Access

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#30]
# Story
- As provider I want to restrict the users that can work with the dev, staging or live landscapes so that only we work on dev and staging and only the need-to-have operators have access to live.

# Motivation
At present everybody at SAP has access to all our landscapes (SAP IdP, in contrast to LDAP, doesn't give us groups). However, that means that everybody has access to our dev, staging, and live landscapes.

# Acceptance Criteria
- [ ] Nobody that we do not want can create projects (or at least shoots) on the dev, staging and live landscapes

# Implementation Proposal
Maybe we could help us with some cluster role on dev, staging and live, that would allow only a dedicated set of users? The basis of that user list could be the users list in [landscape-dev-garden#5](https://github.wdf.sap.corp/kubernetes/landscape-dev-garden/issues/5).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual test tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests or added manual test tickets?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?

**Comment by grolu** [comment]
Restricting access is not handled the dashboard. However, if a user does not have rights to create projects, we should disable the button #234
