### ISSUE TITLE
Enable the support of io1 volumes while creating AWS clusters

### ISSUE THREAD

**Issue by PadmaB** [gardener/dashboard#306]
Expose this configuration in dashboard once the support for io1 volumes is supported in Gardener.
**Ref:** https://github.com/gardener/gardener/issues/726

**Comment by grolu** [comment]
@vlerenc How important is this setting? Is this something we want to have on the UI or is this a rather advanced setting that should be configured via YAML? I already talked to Rafael who has no strong opinion on this. Maybe you can share your thoughts... thank you!

**Comment by vlerenc** [comment]
No strong opinion either, so I guess you can also leave it out.

**Comment by grolu** [comment]
Ok, thank you. I will close the ticket for now. If more people start asking for this we can still include it though.
