### ISSUE TITLE
CoreOS Container Linux Version not visible in YAML tab

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/dashboard#315]
For a cluster administrator currently it is not possible to see the CoreOS Container Linux Version in the Dashboard in the YAML tab at least in an AWS cluster. You only see the name of the image e.g. ami-04d747d892ccd652a. It would be better to see the CoreOS Container Linux Version version at least in a comment e.g.1967.5.0.

**Comment by rfranzke** [comment]
No issue with the dashboard itself - it just exposes the Gardener API.
This problem will go away with extensibility and the redesign of the shoot resource.
