### ISSUE TITLE
More descriptive information for readiness tags

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#325]
We should provide more information about what the conditions stand for. This could be a short description in the condition popper or a more detailed description with an info button (or maybe both, we could have some kind of expandable section with a more button on the condition popper).

@rfranzke @adracus Can someone of the Gardener Team help us and provide some descriptive texts?

A related task is to hide certain conditions from users without the admin role. We should discuss if we want to make this configurable via dashboard configuration.

**Comment by rfranzke** [comment]
* `APIServerAvailable` indicates whether the shoot's kube-apiserver is healthy and available.
* `ControlPlaneHealthy` indicates whether all control plane components are up and running.
* `EveryNodeReady` indicates whether all nodes registered to the cluster are healthy and up-to-date.
* `SystemComponentsHealthy` indicates whether all system components in the `kube-system` namespace are up and running.

**Comment by rfranzke** [comment]
> A related task is to hide certain conditions from users without the admin role. We should discuss if we want to make this configurable via dashboard configuration.

Why should we do that? Every user can easily query the conditions via kubectl, so why do we want to hide anything in the dashboard?

**Comment by grolu** [comment]
Thank you for providing the descriptions. I will check back with the team if they are sufficient (understandable for someone who is not familiar with the technical details).
The question if we should hide some conditions has been raised in an internal discussion.

**Comment by shturec** [comment]
`SystemComponentsHealthy` indicates whether all system components in the kube-system namespace are up and running.
@rfranzke which are the system components considered here?

`ControlPlaneHealthy` indicates whether all control plane components are up and running.
@rfranzke what is it beyond the API server that is considered here?

**Comment by shturec** [comment]
@rfranzke some [background](https://github.wdf.sap.corp/kubernetes/auditlog-extension/issues/162#issuecomment-1491012) wrt the last paragraph about filtering some dashbhoard content by role.

**Comment by rfranzke** [comment]
> which are the system components considered here?

All the pods we deploy into `kube-system`: calico, coredns, node-exporter, vpn-shoot, kube-proxy(, optional addons)

> what is it beyond the API server that is considered here?

Everything in the shoot namespace in the seed: etcd, kube-controller-manager, kube-scheduler, machien-controller-manager, monitoring stack, logging stack, cloud-controller-manager, ...

> Also, it seems that etcd readiness is also considered part of the APIServerAvailable but you couldn't infer that in any way could you?

When sending a request to the `/healthz` endpoint of the kube-apiserver it will internally check etcd health and only report OK if the etcd also reported ok

**Comment by vlerenc** [comment]
> Why should we do that (hide `CP`)? Every user can easily query the conditions via kubectl, so why do we want to hide anything in the dashboard?

See other discussion (don't have ticket at hand now). Users are obviously confused and things may seem rougher than actually the case. Yes, also as written in the other ticket, users can see the condition still and I wrote, that's not optimal. In practice however, people always get their cluster status from the Dashboard and are alarmed for no good reason sometimes. `CP` stands predominantly for components they don't see and don't have under control (especially since there is now `API` for which they care).

**Comment by shturec** [comment]
@rfranzke thanks for [clarifying](https://github.com/gardener/dashboard/issues/325#issuecomment-470881384). That comment is the only description of what's behind those terms I've found for now. Except for a brief touch [here](https://kubernetes.io/blog/2018/05/17/gardener/#addons). At least considering System Components. Correct?

**Comment by grolu** [comment]
We will hide CP readiness tag for non admins (hard coded) in the next release. The descriptions will be included as part of #317

**Comment by grolu** [comment]
More descriptions
 
API = Availability of the kube-apiserver endpoint of the cluster. If this is red then there is no interaction with the cluster possible. The workload running on the cluster is most likely not affected. Please be aware we have currently some issues with false positives on this check, because Gardener run these checks centrally from a cluster on GCP and there seem to be some issues with sporadic network interruptions between GCP and Azure and AWS etc. We are working with high pressure to get rid of these false positives.
N = State of the cluster nodes. If this is not green there is probably an issue with the cluster nodes and they are not ready for some reason. In worst case there couldn’t be not enough capacity for the moment to schedule all the workloads/pods running in the cluster and that might be cause a disruption on workload side.
SC = Status of the system components which Gardener need to deploy in the kube-system namespace of a cluster. For instance if the vpn-shoot pod in the cluster does not run it has the effect that port-forward from the apiserver of the cluster does not work and you want be able to use the Kubernetes proxy functionality or to fetch logs from pods etc. Gardener has a component running beside your Kubernetes control plane on our Seed clusters which is responsible to manage these system components and should automatically take care that these components become healthy again. The impact of these health checks is in the most cases very limited.
