### ISSUE TITLE
Navigation fails with "Failed to fetch shoot"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#326]
#####  Version the issue has been seen with
1.28.0

##### Expected behaviour you didn't see
Dashboard to handle properly the navigation between projects - when new project is selected, the shoots from the newly selected project to be listed.

##### Unexpected behaviour you saw
Dashboard fails with `Failed to fetch shoot`.

##### Steps to reproduce:
1. Open the dashboard.
2. Select a project from the sidebar. 
Ensure that after the selection the url is `<host>/namespace/<project-name>/shoots/` and all shoots in the project are listed.
3. Select a shoot. 
Ensure that after the selection the url is `<host>/namespace/<project-name>/shoots/<shoot-name>` and the shoot details are listed.
4. Select another project from the sidebar.
Ensure that the url changes to `<host>/namespace/<new-project-name>/shoots/<shoot-name>`, the dashboard searches for the same `shoot-name` in the newly selected project. And this all result in `Failed to fetch shoot` error.

**Comment by petersutter** [comment]
we have fixed this issue already in the webterm branch, we need to check if we can cherrypick..

**Comment by grolu** [comment]
Thank you foir reporting this issue. We are aware of this issue. It has already been fixed in a feature branch. @petersutter woulod it be possible to cherry pick this fix to include it in next weeks's release?

**Comment by ialidzhikov** [comment]
Thank you!
