### ISSUE TITLE
Configure Hibernation Button Shows Incorrect PopUp

### ISSUE THREAD

**Issue by mnimm** [gardener/dashboard#333]
When you click the hibernation settings-button in the lifecycle section of the cluster overview, you get to the "Configure Maintenance" popup. I would have expected a "Configure Hibernation" menu, since maintenance has a separate settings-button just below.

**Comment by grolu** [comment]
Hi,
thank you for reporting the issue. You are right, obviously the button "Configure Hibernation" should open "Configure Hibernation" and not "Maintenance". Actually, the "Configure Hibernation" button got accidentally merged from a feature branch and somehow slipped into the release. We already finished developing the Feature (#308) and it will be included in the next release. Then the button will work as expected.

Cheers,
Lukas
