### ISSUE TITLE
Create/View/Modify Shoot Cluster Spec (Mid-Term Mitigation)

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#34]
This is a mid-term mitigation for #23: Can we please allow the user in the creation dialog and later in the details view to create/edit (ideally in-place) the yaml definition of the shoot cluster (spec only ?).

**Comment by holgerkoser** [comment]
Evaluating usage of [Vue-Codemirror](https://surmon-china.github.io/vue-codemirror/) component in combination with vuetify.

**Comment by vlerenc** [comment]
I was wondering, if we go this path, whether we can integrate the yaml editor also in the shoot cluster creation dialog and how that would interleave with the dialog?

If not, what would be the way for a user to create a cluster from the start with the right configuration (for the domain stuff, that's even the only time this can be set, i.e. only at creation time the domain can be set).

**Comment by holgerkoser** [comment]
If you think it makes no sense I will stop my work. I thought we allow everything and report errors if something is not possible or does not work right now.

**Comment by grolu** [comment]
Implementation is done for cluster details. Option to edit shoot yaml before creation is still missing. See also #208

**Comment by vlerenc** [comment]
Then let's close this one since #208 is also open.
