### ISSUE TITLE
Shoot spec should not contain DNS section per default

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#340]
The dashboard is reading the default domains in the garden cluster in order to compute a DNS domain for a shoot (shootname.project.<default-domain>). This is not necessary anymore - since a couple of releases Gardener does this computation on its own.
The recommended way (with Gardener v0.20.0) will be to set `dns: {}` when creating shoots that shall use a default domain.

**Comment by grolu** [comment]
@rfranzke if this is critical we can include it as fix in the next release, if not it well be done as part of #208
