### ISSUE TITLE
Bring-Your-Own-Cluster Registration (Plant) in Dashboard

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#344]
Since Gardener has merged support for plant resources, we need to integrate them into the dashboard. The plan is to show them along with the shoots in the same list, maybe with an indicator that identifies them as plants. Also, we want to provide (limited) cluster details for plants.

**Comment by grolu** [comment]
close when https://github.com/gardener/gardener/issues/6348 is done

**Comment by timebertt** [comment]
/close
as `Plants` were dropped with https://github.com/gardener/gardener/pull/6472
