### ISSUE TITLE
Kube-Cluster Access for Dashboard

### ISSUE THREAD

**Issue by vasu1124** [gardener/dashboard#35]
dashboardUrl should now be pointing to `/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`

Background: several incompatible changes were put forth by the community:
a) change to proxy subresource (with v1.8.0)
b) change to https (with v1.7.1)
for ref, see history of https://github.com/kubernetes/dashboard/commits/master/src/deploy/recommended/kubernetes-dashboard.yaml

(we probably can expect further incompatible changes, which might require some kubernetes-dashboard version dependant configmap)

**Comment by petersutter** [comment]
fixed on the new dev landscape (for the old dev system the config changes are already checked in and just need to be applied, however this system is deprecated anyhow).

yes you are right, in the future we might require such a kubernetes dashboard version dependant configmap
