### ISSUE TITLE
Control Plane Tweaking

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#36]
# Story
- As user I want to tweak certain features like alpha/beta switches or allowing privileged containers or not, so that I can do more things with my clusters, even though not all are production-ready yet in Kubernetes.

# Motivation
The Gardener allows to tweak the configurations of API server, controller manager, scheduler and kube-proxy as well as allowing privileged containers or not, but we haven't exposed that yet (unless we are fine with #34).

# Acceptance Criteria
To be defined in more detail. We need to investigate first (with Rafael F.), whether we can offer some pre-selection or how to actually allow the configuration (outcome can also be to leave it at #34, but then we need some documentation and it will not be very convenient).
- [ ] During cluster creation/update the user shall be able to switch on/off privileged containers support
- [ ] ...

# Resources
See [Gardener](https://github.wdf.sap.corp/kubernetes-attic/garden-operator/issues/198).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual test tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests or added manual test tickets?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you informed the documentation developers about user-relevant changes?

**Comment by vlerenc** [comment]
Are #208 and #302 replacing this one? If so, let's close this one (or the other one).

**Comment by grolu** [comment]
I don't know... Yes I guess we can close this one if we do not plan to offer anything besides the yaml  editor.

**Comment by vlerenc** [comment]
Not sure what your plans are in regards to the cluster creation dialog?

**Comment by grolu** [comment]
currently not planned to implement in the UI @vlerenc do you think that we should invest here?

**Comment by vlerenc** [comment]
Well, people don't know what is possible. We can also strive for a pragmatic approach. I believe, there were issues with context-sensitive help in the yaml editor and even if not, it would not be obvious where to look/check. One colleague proposed to start off with something like the Gardener examples manifests when you switch during cluster creation to the yaml editor. Then users would see the options. That would definitely help. WDYT?

**Comment by grolu** [comment]
We could start by providing at least a link to the examples. Moreover, we already planned to support to export the configuration on the create cluster dialog into an URL. We could encode the yaml into the URL and this way it would be possible to provide Create Cluster links with templates for different purposes.

**Comment by grolu** [comment]
We now support code completion in the cluster YAML editor. Do we agree that this helps people to figure out what can be configured and that we can close this issue?
see PR #462
