### ISSUE TITLE
Cross-Project Cluster Fleet Management

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#365]
We have seen questions around how the Dashboard could support cross-project cluster fleet management. While we have an aggregated clusters view for admins, we don't have that for end users and in the past this view brought complexity. Also, if we do that, it is similarly decoupled from the other navigation entries like secrets or members.

**Comment by grolu** [comment]
@vlerenc , the "All Projects" view is also available for regular users.

**Comment by vlerenc** [comment]
What, really? Thanks! I knew, we spoke about it in the beginning, but since I am admin everywhere, I didn't know. Thanks, then I can close this ticket, I guess.
