### ISSUE TITLE
miss aligned icons in the cluster overview

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#366]
Icon for aliCloud is not on baseline.

<img width="339" alt="Bildschirmfoto 2019-04-17 um 13 40 56" src="https://user-images.githubusercontent.com/1155039/56285998-d7d9df00-6118-11e9-99fe-3e2dd1996edc.png">

**Comment by freegroup** [comment]
additional you are using the "Amazon" Icon and not the AWS icon....  :-)

**Comment by vlerenc** [comment]
There is another ticket on logos and colors #18.
