### ISSUE TITLE
Font issue in China

### ISSUE THREAD

**Issue by jia-jerry** [gardener/dashboard#367]
Hi Colleagues,

We met a font issue when we access Dashboard from China. 
The root cause is https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700|Material+Icons can't be accessed from China because of China Great Firewall.

Is possibel for us to add this font resource in our dashboard project?

**Comment by grolu** [comment]
Hi Jerry,
Is this the only resource that is causing issues in China? As we also include other external resources it would be great if you could give us a list of resources that cannot be accessed so that we can decide on how to handle this.

**Comment by jia-jerry** [comment]
Hi Lukas,

I found this https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700|Material+Icons can be access in China now.

Let's keep unchanged by now.

If I meet this again, I would like to collect all un-accessible links then. Thanks a lot.

**Comment by jia-jerry** [comment]
Hi @grolu ,
Sorry I reopened the issue. I encountered this issue again.  Would you please add css file https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700|Material+Icons to dashboard local service? Thank you in advance.

Regards,
Jerry
