### ISSUE TITLE
Improve Secrets Help for Azure, GCP and OpenStack

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#37]
As evident from some internal Slack communication, users struggle to set up their Azure, GCP and OpenStack technical users and permissions. Let's contact @AndreasBurger and @dkistner (for Azure), @DockToFuture and @mliepold (for GCP) and @mandelsoft and @afritzler (for OpenStack) to improve the descriptions with their feedback.

However, it may well be, that we should also give some internal advice/hints (how to apply for a technical user within our company - or any other for that matter), so maybe we have to pull that configuration out? If possible we should avoid it at first (given the other backlog), but the time will come that this may become necessary for the community and us.

**Comment by dkistner** [comment]
For Azure I already started to define a role, which has only the for Gardener required permissions.
It's not complete, because it limits the access to the required services (providers) on Azure, but within those services everything can be done (which is not required). Also added instructions to apply those role.
https://gist.github.com/dkistner/54d3553a32c98c6932d894de93b1eb50

**Comment by vlerenc** [comment]
Thanks @dkistner.

**Comment by vlerenc** [comment]
What can we do to improve also GCP adoption @DockToFuture and @mliepold? Can you also provide a gist? I would then add both to the landing page.

@petersutter and @grolu I suggest to highlight the hint about the IAM enablement as users seem to miss it. What do you think?

**Comment by rfranzke** [comment]
Should we rather add the needed permissions to the [Gardener's `docs` folder](https://github.com/gardener/gardener/tree/master/docs) (maybe in a technical way so that the Dashboard can extract the information from there)?

**Comment by vlerenc** [comment]
Well, that was the initial idea and question half a year ago. I would very much appreciate a solution without duplication and double-, triple, and quadruple maintenance (gardener, dashboard, landing page, gist).

On the other hand, double maintenance cannot be prevented right? The access permissions that are required are buried implicitly in the botanist code and configuration. Anyway, it would still be the right repo to describe it. Then we could drop the stupid gists and let the landing page refer it and the dashboard maybe embed it.

That would be a definite +1 👍.

**Comment by mliepold** [comment]
I will provide some technical documentation too for GCP.
But I also would appreciate a location in the gardener that could be directly referenced by the dashboard.

**Comment by mliepold** [comment]
For now I also provided a gist with the technical instructions for GCP:
https://gist.github.com/mliepold/9a8b1dde5c1d2965cfb6c8999e10b6c9

**Comment by vlerenc** [comment]
Are we OK-ish now and can close the ticket?

**Comment by grolu** [comment]
The reason why this is still open is that we had plans to read documentation from somewhere else and do not hard-code in the dashboard. If we decide not to do this (which is probably the case as we have more important things to do), we can close this.

**Comment by vlerenc** [comment]
OK, well, it would be good to do that (single source of truth), but then again, it's not likely to happen, so let's close it for now, I guess?

**Comment by grolu** [comment]
Ok for me
