### ISSUE TITLE
No image for "techuser"

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#387]
I noticed that when I create a technical user in the members tab with the name "techuser" it has no proper image or it appears so:

<img width="523" alt="Screenshot 2019-05-16 at 13 25 17" src="https://user-images.githubusercontent.com/4974203/57850458-470d2680-77de-11e9-98ca-49a67b15ed80.png">

I tried a few other arbitrary names, but they all had images. I retested, same result. Strange?

**Comment by petersutter** [comment]
this seems to be an issue with the gravatar service responding with some 503 error. I also could reproduce the issue but after some reloads in the browser the icon was shown...

**Comment by grolu** [comment]
I also experienced this a couple of times. It seems that the service has outages from time to time. We could include the robohash library in the dashboard but we still need to rely on the Gravatar service. I would keep it as it is if that is ok for everyone.

**Comment by vlerenc** [comment]
Sure.
