### ISSUE TITLE
[Feature]UI support to manage labels/taints/annotations on workerpool

### ISSUE THREAD

**Issue by PadmaB** [gardener/dashboard#390]
Workerpool now supports labels/taints/annotations which is then propagated to actual nodes via MCM. Kindly refer the example Shoot [yaml](https://github.com/gardener/gardener/blob/master/example/90-shoot-aws.yaml#L30-L37) for details 

For now, the user has to directly edit the Shoot yaml in the dashboard. However, it will be convenient to have UI support to manage labels/taints/annotations on the workerpool with ease

**Comment by grolu** [comment]
Also, consider adding the other missing options: https://github.com/gardener/gardener/blob/master/example/90-shoot-aws.yaml

**Comment by grolu** [comment]
I discussed this with @vlerenc. We will not support editing taints, labels, annotations for now as it is an expert feature that does not need to be exposed via the UI.
However, I added support for configuring Worker Image as well as Max. Surge
