### ISSUE TITLE
User Monitoring Integration

### ISSUE THREAD

**Issue by dkistner** [gardener/dashboard#396]
The Shoot clusters managed by Gardener come with some end user monitoring capabilities. 
We should also have options to enable, disable, control these capabilities and provide access to the user monitoring via the dashboard.

There are two scenarios which need to be covered.

### Register for Shoot cluster alerts
Users can register an email address to receive the Shoot cluster alerts. This can done by annotating the `Shoot` resource with a valid mail address as the following:
```
garden.sapcloud.io/operatedBy: "john.doe@example.com"
```

We should extent the cluster creation dialog to allow to register for the alerts.
In addition we should also allow to register, unregister for alerts and to change the receiving mail address in the Shoot detail page.

In all cases we should check if the mail address is valid already in the dashboard.

The option to register for alerts via mail requires to have a smtp configuration in place. These configuration is located in a secret labeled with `garden.sapcloud.io/role: alerting-smtp` in the garden cluster. If no secret of this kind exists, we shouldn't display an option to register for alerts.

### Access User Monitoring
Beside the monitoring for operators, there will be also an user facing monitoring part for Shoot clusters. This consists of a dedicated Grafana which has an own set of dashboards for users. This user Grafana will be always available and we should therefore integrate it into the Shoot detail section.

The link to the `user` Grafana should be visible for every Project member, owner and operators/admins (there will be dedicated credentials and ingresses for this Grafana). 
The link to the `operator` Grafana should be visible only for operators/admins (as it is already today).

The user monitoring part is now merged (see the respective PRs)
- https://github.com/gardener/gardener/pull/1000
- https://github.com/gardener/gardener/pull/1099

**Comment by rfranzke** [comment]
See also https://github.com/gardener/gardener/pull/1000#issuecomment-500812890

**Comment by wyb1** [comment]
End-user monitoring is now always enabled. See [this](https://github.com/gardener/gardener/pull/1086).

**Comment by dkistner** [comment]
I have updated the issue description.

**Comment by grolu** [comment]
@dkistner, @wyb1 Wesley already integrated the access to end user monitoring into the dashboard. As it is enabled by default, do we need the other things (enable, disable, register on cluster creation, configure email etc.)?

**Comment by grolu** [comment]
closing issue as it seems resolved
