### ISSUE TITLE
Nothing happens when opening dashboard in IE 11

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/dashboard#403]
Opening the dashboard in Internet Explorer 11 results in an empty page. It would be helpful to show some text that it is not supported.

**Comment by grolu** [comment]
Internet Explorer 11 support has been officially stopped by Microsoft as of January 2020.  Recent Microsoft Edge Browsers show a decent error message, so I mark this issue as resolved.

![Screen Shot 2020-03-31 at 14.40.17.png](https://images.zenhubusercontent.com/5a9e461b4b5806bc2bc98cf3/595c6aa0-0257-4d84-8bd1-04ef9bbee9b7)
