### ISSUE TITLE
Disable cluster delete button in garden namespace

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#415]
The garden namespace is only accessible to operators. However, to prevent any deletions by mistake of shoots in this reserved namespace the delete button should be disabled.
Optionally introduce a config flag to enable/disable this behaviour of the UI

**Comment by mvladev** [comment]
`garden` namespace is not special. I could name it `garden-system` or something similar and install my components there.

**Comment by petersutter** [comment]
currently we several places in the dashboard where the garden namespace is hardcoded. In addition, even the gardener itself has a `GardenNamespace` constant.
Currently we live with this assumption until there is a need to make it more dynamic, but then also gardener has to adapt.

**Comment by grolu** [comment]
We discussed that we could (instead of hardcoding Garden namespace) also disable critical actions (e.g. delete hibernate, etc.) for clusters with purpose INFRA
