### ISSUE TITLE
Self-Termination Information/Warning

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#42]
# Stories
* As user I want to know when my trial cluster is terminating, so that I know for how long I can use it.

# Motivation
Clusters that are created with trial secrets will usually self-terminate (default is 7 days, but it depends). The user should know of this.

# Acceptance Criteria
- [x] When the cluster is created, please let him know that it will self-terminate and when (depends on the secret that is used)
- [x] When the cluster is shown in list or details view, please let him know when it will self-terminate
  - [x] When the cluster is near its end of life (last 24h) make this even more visible (color, boldness, whatever seems appropriate and fits the technology and UI design)

# Definition of Done
- [x] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [x] Integration Tests are provided: Have you written automated integration tests?
- [x] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by mliepold** [comment]
Annotation at the Shoot resource:
"shoot.garden.sapcloud.io/expirationTimestamp"

**Comment by petersutter** [comment]
see also https://github.com/gardener/gardener/issues/81
