### ISSUE TITLE
Show Estimated Cluster/Node Costs

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#424]
Some time ago, @freegroup suggested to show the estimated costs for a cluster. We also would like to show the actual costs. We didn't work on it, because it's actually a lot of work to get to the data we need. All providers have different APIs, we deploy different resources, costs even vary by concrete (instance/storage/LB) type and even/also region and then there are contractual settlements and offers such as recommended instances and the like. However, there are a few Open Source projects that may solve this problem, at least for instance types, which is the biggest head ache (hundreds if not thousand different price entries):
- https://github.com/banzaicloud/cloudinfo
- https://github.com/banzaicloud/spot-price-exporter
- https://github.com/banzaicloud/telescopes

With this we actually have a chance to calculate at least estimated costs for a cluster. At first just for the nodes, but adding on top storage (based on the storage classes we deploy into a cluster) and also load balancers as the two other main cost drivers, shouldn't be too difficult either. The rest is less relevant (looking at our own IaaS bills) or hard to estimate (if dynamic like network traffic).

We can start simple and grow:
1. Estimated costs for the nodes only (respecting a hibernation schedule if specified)
2. Actual costs for the nodes only (respecting a hibernation schedule if specified)
3. Adding node disks and the VPN (if it's still around) and possibly nginx ingress LB costs
4. Implementing a metering component not only for the control plane, but also for the workload that scrapes the cluster (no hardcoded VPN/nginx LB anymore) for actual PVs and LBs and compute full cluster costs for nodes, storage and LBs 

Note: This is not yet a real epic or story. There is a lot to plan, design, and think through in terms of what we can and should do, what our users want to have and like to see. It's also not necessarily only a Dashboard topic, but maybe predominantly in this case. Still, the building blocks like a service offering the price entries or metering will be separate entities.

cc @mliepold

**Comment by grolu** [comment]
We should also show costs for the control plane cross charging

**Comment by vlerenc** [comment]
Follow-up ticket, see: https://github.tools.sap/kubernetes/security-compliance-backlog/issues/151
