### ISSUE TITLE
Remove space when members are added to project

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/dashboard#427]
When you add a member to a project containing a space at the end of the e-mail address 'test@test.com '  this is not visible in the Dashboard but the user owning the e-mail 'test@test.com' does not see the project he was added as member. In addition he cannot be deleted anymore via the dashboard. Thus I propose to remove leading and ending spaces.

**Comment by holgerkoser** [comment]
Leading spaces are not a problem but trailing spaces are the reason why the member cannot be removed. However the UI returns a success message but the member is still there.
