### ISSUE TITLE
Support multiple AZs for the OpenStack shoots

### ISSUE THREAD

**Issue by kayrus** [gardener/dashboard#432]
* Gardener dashboard has to allow to select multiple AZs for the shoot in the create cluster modal windows
* Dashboard should not generate JS errors, when there is an openstack shoot cluster with the multiple AZs and one workers network (see https://github.com/gardener/gardener/pull/1192 and screenshots below)

![Screenshot_20190710_131057](https://user-images.githubusercontent.com/4047483/61024016-8c983b00-a3ac-11e9-88d2-3e1c95357ca4.png)
![Screenshot_20190710_131024](https://user-images.githubusercontent.com/4047483/61024017-8c983b00-a3ac-11e9-923c-b5111959a593.png)
![Screenshot_20190710_112726](https://user-images.githubusercontent.com/4047483/61024019-8c983b00-a3ac-11e9-8f87-a619cf796ead.png)

**Comment by grolu** [comment]
@kayrus thank you for reporting this!
Part of this is already done with #416 
However, I'll need to have a closer look on the JS errors.

**Comment by grolu** [comment]
Hi @kayrus I tried to reproduce the issue but I don't get any JavaScript errors when I try to configure worker groups for a multi-zone OpenStack cluster. Can you explain to me in more detail what you did to cause this behavior. Does the issue only occur when the azs share one worker node network?

**Comment by kayrus** [comment]
>  Can you explain to me in more detail what you did to cause this behavior.

nothing. I just used the binary with this fix: https://github.com/gardener/gardener/pull/1192/files

> Does the issue only occur when the azs share one worker node network?

Yes, one CIDR and multiple AZs.

**Comment by grolu** [comment]
Ok I will need to wait for this to get released and deployed into dev landscape as I do not want to setup a gardener installation for this. I just tried with two azs / two worker networks and this worked fine for me.

**Comment by kayrus** [comment]
The #416 branch has been tested and so far it works fine.
