### ISSUE TITLE
Disable seed cluster update via dashboard

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/dashboard#435]
Seed cluster updates are the most challenging updates, because that's an update that violates the shoots maintenance time windows.
Such updates must be qualified and accompanied in our dev/staging landscapes. 
Therefore it should not be possible to do such updates "uncontrolled" in the dashboard.

**Comment by grolu** [comment]
We could disable updates depending on the purpose. We could disable updating infrastructure clusters. See also #415.
