### ISSUE TITLE
assert.ok(_.get(config, path), `Configuration value '${path}' is required`)

### ISSUE THREAD

**Issue by BennieMeng** [gardener/dashboard#438]
i run this repo by step, but  get follow  issue: 
assert.ok(_.get(config, path), `Configuration value '${path}' is required`),
i also add config file. 
i need help to know where is wrong.

**Comment by petersutter** [comment]
Hi @BennieMeng, sorry for the late response. What is the error message that you see?

**Comment by grolu** [comment]
Closed as no response. Please re-open if issue still exists.
