### ISSUE TITLE
Add additional OpenStack Secret fields

### ISSUE THREAD

**Issue by afritzler** [gardener/dashboard#445]
This is related to the issue in the extension repo: https://github.com/gardener/gardener-extensions/issues/154

Currently we are in the progress of adding those fields
- `DomainID` (or `DomainName`, at least one has to be provided)
- `TenantID` (or `TenantName`, at least one has to be provided)
- `UserDomainName` (optional)
- `UserDomainID` (optional)

We need to adjust the secrets creation dialog in the dashboard here as well.

**Comment by grolu** [comment]
What about additional shoot configuration options (loadBalancerClasses)

**Comment by kayrus** [comment]
@grolu them too

**Comment by grolu** [comment]
See also #471 #446

**Comment by grolu** [comment]
@dkistner @mandelsoft @MartinWeindel can someone from the Open Stack experts comment if we still need to keep this open.

**Comment by kayrus** [comment]
Yes, we need. There could be system users from another domains.

**Comment by grolu** [comment]
Okay then what is the status of https://github.com/gardener/gardener-extensions/issues/154
...and what shall be added to the dashboard secret dialog as of **now**
