### ISSUE TITLE
Shoot list is empty / Websocket issue

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#449]
We have seen that the shoot list on production clusters sometimes does not show any clusters. The list appears empty, even though they can be fetched directly from the kube apiserver e.g. using kubectl. 
Restarting the dashboard pod solves the problem temporarily.

We have seen that this issue starts to occur with mass disconnections of websockets, e.g. when the nginx ingress controller detects a configuration change and restarts it's backends.

I could reproduce the issue locally and https://github.com/websockets/ws/issues/1617#issue-479369085 is a pretty good description of what I saw in the debugger. The issue seems to be solved with [`ws` 7.1.2](https://github.com/websockets/ws/releases/tag/7.1.2).

There is already a [PR](https://github.com/socketio/engine.io/pull/587) on `engine.io` to upgrade to `ws` 7.1.2

**Comment by grolu** [comment]
socket.io 2.3.0 has been released 5 days ago. Can you verify that the fix is included and solves the issue @petersutter

**Comment by petersutter** [comment]
The fix is part of engine.io 3.4.0.
But the socket.io release contains engine.io 3.3.1 -> so no, unfortunately not yet within the latest socket.io release

**Comment by grolu** [comment]
still no new release as of today

**Comment by grolu** [comment]
re-checked, actually engine.io 3.4.0 is part of socket.io 2.3 so updating the dependency will solve the issue. @petersutter will take care.
