### ISSUE TITLE
Cluster Operation Retry Button

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#45]
@rfranzke and @mandelsoft implemented a cluster operation retry in the Gardener that can be initiated with an annotation at the shoot resource. To expose this functionality to our users, we can now add some retry button or similar means to the Dashboard for failed shoot clusters (operations).

**Comment by rfranzke** [comment]
When the Gardener does no longer retry an operation it sets the `.status.lastOperation.state` of the respective Shoot cluster to `Failed`.
Currently, the dashboard does not allow to re-trigger the Gardener to start the operation again.

Please show a button in the dashboard for those failed clusters which a user may click to make the Gardener start reconciling the cluster again.
Technically, the button should set an annotation `shoot.garden.sapcloud.io/operation=retry` on the Shoot.

**Comment by petersutter** [comment]
should the button be hidden in case the shoot has the annotation
 `shoot.garden.sapcloud.io/ignore=true` ?

**Comment by petersutter** [comment]
we could discuss in the UI sync if we want to get rid of one of the retry buttons (e.g. the one in the popover as you already have the retry button right next to the status icon)

![Screen Shot 2018-05-25 at 16.51.29.png](https://images.zenhubusercontent.com/5a269e418a75884b9089eebb/708b22bc-a58b-4930-89c1-819e28e6bf51)
