### ISSUE TITLE
Add an option to disable the hibernation option by default

### ISSUE THREAD

**Issue by kayrus** [gardener/dashboard#459]
In some openstack cloud providers there is no need to hibernate clusters, because the project is charged by the overall quota, not by the amount of running resources. Therefore the hibernation option during the shoot creation is useless.

Dashboard has to have an option to disable the hibernation by default during the shoot cluster creation dialog. If this option is relevant, then operators can enable this option for the dashboard.

**Comment by vlerenc** [comment]
Out of curiosity: Is there no advantage for the infrastructure provider? No overcommit, also not even an environmental advantage (less energy wasted/less money spent/less environment footprint in terms of CO2 and whatnot)?

**Comment by kayrus** [comment]
@vlerenc not sure about the CO2, but there is no hypervisor overcommit enabled.

**Comment by vlerenc** [comment]
Well, and I always thought, CPUs would clock down when not used and save power.

**Comment by grolu** [comment]
It is possible to configure default hibernation schedules per landscape. If you only have one cloud provider, removing the default schedules from your dashboard configuration may already solves your issue. If you need different default hibernation schedules per cloud provider / profile or want to disable the hibernation feature completely, this is a different story. We would then need to discuss the priority and if this something one want to configure on cloud profile level.

**Comment by kayrus** [comment]
I was not aware that the hibernation option depends on the cluster purpose. It seems this issues doesn't make sense.
