### ISSUE TITLE
Hide Monitoring Endpoints for Non-Admins

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#46]
Let's please hide the monitoring endpoints for non-admins (like seed and journal), so that "normal" users can't see our monitoring.

**Comment by petersutter** [comment]
The seed information is only visible if you have access to the garden namespace (which only admins should have) and the journal is also only visible for admins

**Comment by vlerenc** [comment]
I was asking about the monitoring endpoints/URLs (below the dashboard URL). Those are visible to everybody (but everybody shall not do ops right now - only we do ops right now).

Can we please treat those like seed/journal, i.e. expose them only to admins?

**Comment by petersutter** [comment]
Oh ok sorry, I misread that.
I have just added this check.

**Comment by vlerenc** [comment]
Great, thanks!
