### ISSUE TITLE
gardener/dashboard could not show expired Kubernetes versions

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#464]
Steps to reproduce:
1. Add a Kubernetes version in a CloudProfile with `expirationDate` <= `time.Now()`
2. Navigate to `Create Cluster` (`$HOST/namespace/$NAMESPACE/shoots/+`)
3. Ensure that the expired Kubernetes version is listed in the `Kubernetes versions` dropdown.

Ref gardener/gardener#1363

**Comment by grolu** [comment]
Hi,
we currently do not evaluate the expirationDate for Kubernetes versions. Have you entered the version in the offeredVersions array? We do not evaluate the offeredVersions, only the versions array.

**Comment by ialidzhikov** [comment]
From the PR release notes:
> The `.spec.<cloud>.constraints.kubernetes[].versions` field in the `CloudProfile` is deprecated and will be removed in the future. It is now replaced with a list of offered versions (`.spec.<cloud>.constraints.kubernetes[].offeredVersions`). Each version can have an `expirationDate` which specifies the time after all shoots that are using this version and opted-out of automatic Kubernetes patch version updates will get forcefully updated to the latest Kubernetes patch version for the used `<major>.<minor>` version. Example: The `CloudProfile` specifies `(1.14.2, 2019-08-08T14:00:00Z)` and `(1.14.5)` as possible versions for `1.14`. A shoot that is opted-out of automatic updates uses `(1.14.2)`. In its maintenance time window it won't be updated to `1.14.5` before `2019-08-08T14:00:00Z`.

**Comment by grolu** [comment]
I talked to @rfranzke, the offeredVersions is only a temporary workaround in the old cloud profile, when we switch to the new cloud profile resource, the versions with expirationDate that you find under offeredVersions will be renamed back to versions. We are currently evaluating when and how to migrate to the new resources.

**Comment by grolu** [comment]
will be done as part of #457
