### ISSUE TITLE
Copy to Clipboard" didn't work anymore in the secret dialog

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#465]
it is possible to copy the secret in the cluster detail, but not in the dialog.

<img width="1114" alt="Bildschirmfoto 2019-09-30 um 17 39 47" src="https://user-images.githubusercontent.com/1155039/65894137-8ad98480-e3a9-11e9-8ccf-37e01b5b321c.png">

**Comment by petersutter** [comment]
@holgerkoser is already working on a fix
