### ISSUE TITLE
Add an ability to define only allowed OpenStack domains for secrets

### ISSUE THREAD

**Issue by kayrus** [gardener/dashboard#471]
When Gardener is available only for selected OpenStack domains, the secrets dialog should allow to select only allowed domains.

**Comment by kayrus** [comment]
With Gardenlet, this should not be an issue, since in theory it will have an access to any domain.
/cc @afritzler

**Comment by afritzler** [comment]
Well, that is partially true. With the Gardenlet we still need to "enable" a particular domain by installing and registering the Gardenlet there. So the requirement here still makes sense.

**Comment by grolu** [comment]
@afritzler how would the dashboard be able to determine the "allowed" domains?

**Comment by afritzler** [comment]
Currently we can´t really. At the end the domain must match the domain of the seed which has been created by the Gardenlet.

**Comment by grolu** [comment]
As far as I udnerstand, we cannot solve this now. I will close the ticket. Please re-open or open a new ticket if we have a plan on how to support this.
