### ISSUE TITLE
Show expiring versions in Dashboard

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#489]
Kubernetes versions as well as machine images can have an expiration date after which an update of the shoot cluster will be enforced. Currently, we show these dates only as part of the drop down. We need to show this information more prominent to the user, as part of the cluster list (if version is about to expire) and also on the cluster details page.
We also need to consider the additional properties (preview, deprecated, ...)
As part of this issue we can also discuss if we want to show the expiration date as dynamic value (in xxx days) or as date (as of now).

**Comment by grolu** [comment]
Also respect version states (expired, preview, supported...) as soon as they are available

**Comment by vpnachev** [comment]
Version types are now implemented and available https://github.com/gardener/gardener/issues/1577

**Comment by grolu** [comment]
@vpnachev What exactly is the scope for the Dashboard? I talked about this with @RaphaelVogel months ago, but cannot remember exactly. Right now, we filter versions that are expired according to the `expirationDate` - should we also filter images / k8s versions with the classification `expired`? Or can we expect that the date always gives the correct information. Other than that, my current understanding is that we display the classification in the selection dialogs, and that we always try to select the newest `supported` version (in favor for a `deprecated` or `preview` version).
Is there something else to do?

**Comment by vpnachev** [comment]
`expired` is a logical state not available in the API, so you have to always compute it from the expiration timestamp and current date.

My personal opinion is that the dashboard should show some warnings on the shoot and shootlist pages when the cluster is using deprecated version or version that will expire in some time (e.g. 2 weeks, but maybe it makes sense to make this configurable).

The warning message might need to be different for expiring and deprecated versions. Basically, for expiring cluster I would prefer something like
```
Dear user,
Your cluster <name> is using OS version that will expire on <expiration date>. 
In the first maintenance window after this date of your shoot cluster, the OS version will updated to latest supported version. 
You can find more information [here](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_versions.md)
```

```
Dear user,
Your cluster <name> is using k8s version that will expire on <expiration date>. 
In the first maintenance window after this date of your shoot cluster, the k8s version will updated to latest supported version. 
Note, if there is no patch versions of the current minor version, even the minor version will be updated to the first supported minor version.
You can find more information [here](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_versions.md)
```

For more details check [this](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_versions.md)

cc @danielfoehrKn

**Comment by grolu** [comment]
Thank you @vpnachev. After reading the document, I have still one question: What about unclassified versions? According to the document, Gardener cannot make decisions on the `logical state`. What does that mean? Is an unclassified, not expired version treated as `supported` version? Does Gardener migrate shoots with deprecated / expired versions to this version or not?

**Comment by grolu** [comment]
In addition to my previous comment - It is not really clear to me how gardener treats (automatic) version updates in general. Without classification, Gardener always updated the cluster / machine image to the latest available version (semver compare). Is this still the case - even if the current version is still classified as `supported`?
