### ISSUE TITLE
Auto-close Journal Tickets when cluster recovers

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#492]
Once the reconcile succeeds for a shoot and there exists a journal with certain labels (to be configured), like `insufficient-privileges`, `quota-exceeded`, `configuration-problem` the journal should be auto-closed, similar to like it is done for deleted shoots.

**Comment by petersutter** [comment]
Currently we have no means to detect this transitioning state. This could change in the future in case we have a shoots cache so we have the old shoot and new shoot to compare against.

**Comment by grolu** [comment]
@petersutter I can move it to the Icebox on Zenhub or we close it for now. WDYT

**Comment by petersutter** [comment]
We can close it for now
