### ISSUE TITLE
Show deployed extensions + versions

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#498]
Today, the dashboard only shows the deployed Gardener version, however, it would be also nice if it could show the registered extensions and the respective versions.

**Comment by grolu** [comment]
related to #452 (prerequisite)

**Comment by petersutter** [comment]
@rfranzke you are talking about the `ControllerRegistration`s, right? How do I find out the version of a controller registration?

**Comment by rfranzke** [comment]
Right now, the only option is to check `.spec.deployment.providerConfig.values.image.tag`, however, this only works for `helm` types and only if the respective chart follows the `image.tag` structure in its `values.yaml`. We might have to think about a better mechanism to expose this information...

**Comment by grolu** [comment]
@rfranzke There is still no better option, right?
I want to display the extensions in the dashboard. For now I will only show the extension name, more details will be added if you tell me what you want to be shown and how to get this information

**Comment by grolu** [comment]
I guess I will start with reading the image tag as you proposed. But it would be really nice to have something better here
