### ISSUE TITLE
Export availability metrics

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#506]
Expose dashboard availability metrics to integrate into alerting and landscape dashboards.

**Comment by grolu** [comment]
Related #447

**Comment by vlerenc** [comment]
Hmm... @grolu we have the Dashboard covered in AvS, so what is this issue about?

As for #447 these would be monitoring changes, but we wouldn't fail the AvS probe, would we?

**Comment by grolu** [comment]
@petersutter can you please comment. I lost overview of all these monitoring related issues.
