### ISSUE TITLE
Keep Shoot in Vuex store while viewing it

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#51]
As an Administrator, I navigation from the "Shoots with issues" list to the details page of a shoot. If this shoot becomes healthy, it will be removed from the shoots with issues list and thus remove from the local vuex store. In this case, I will be left with a broken page as all shoot information i gone but I'm still on the details page.
We should join a dedicated room for this shoot while viewing it, so that it will not be removed from the store while viewing it. In addition, we should inform the user or navigate away in the unlikely event of an actual shoot deletion.

**Comment by vlerenc** [comment]
Option 1 seems the right solution. It is what one would expect when navigating into a cluster and allows to stay there (check secrets, etc). Hopefully, it is also the solution, that is cleanest/easiest to implement?

**Comment by grolu** [comment]
All solutions are implemented and I referenced the respective branches in my previous comment. But yes, option 1 is definitively the easiest one to implement. Let‘s have a look at it (hands-on) in our next UI sync.
