### ISSUE TITLE
Add copy button to the seed and shoot names in the UI

### ISSUE THREAD

**Issue by dansible** [gardener/dashboard#526]
Would it be possible to add a `copy` button to the seed and shoot name parameters in the UI? This would be the same as how the Technical Id, monitoring and logging passwords, etc have a copy button.

**Comment by grolu** [comment]
We can have those buttons on the cluster detail page. On the cluster list, we also show a copy button next to the technical id. I guess it would overload the table if we start adding buttons for more columns (even for those visible by default). We need to discuss how we handle this.

**Comment by grolu** [comment]
Can you elaborate a bit more, why you need this feature? We introduced the copy button as this value needs to be copied quite often (and dashes make it harder to select). Do you also need to copy the other values regularly?

**Comment by dansible** [comment]
@grolu it would just be for the detail page. When troubleshooting issues with shoot clusters, I am frequently needing to copy the seed ID and the cluster name to target the correct seed and cluster respectively using gardenctl. 

See the screenshot with the two proposed locations highlighted:

<img width="1160" alt="Screen Shot 2019-12-13 at 3 30 43 PM" src="https://user-images.githubusercontent.com/25449094/70807914-d69fa580-1dbe-11ea-9b16-ef0031d360d9.png">
