### ISSUE TITLE
Implement Cross Charging Capabilities

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#529]
Add possibility to configure cost objects in dashboard configuration that allow operators to make users set billing operation for projects. Cost information needs to be provided which can be used to show accumulated costs for cluster control planes in the dashboard. The billing information can be used to generate monthly reports for cross charging purposes.

**Comment by vlerenc** [comment]
Can be close right @grolu ?

**Comment by grolu** [comment]
Actually, there is still the task open to expose all the charging and cost information in the dashboard.

**Comment by grolu** [comment]
I closed this in favor for https://github.com/gardener/dashboard/issues/424
