### ISSUE TITLE
Adapt to gardener API Changes

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#536]
Wait for https://github.com/gardener/gardener-extensions/pull/521 to be released and then adapt to the new fields in the shoot spec.
Also adapt to new gardener API `gardener.cloud/v1beta1`
(see also https://github.com/gardener/gardener/releases/tag/v0.33.0)
Purpose is now part of shoot spec: https://github.com/gardener/gardener/issues/1814

**Comment by vpnachev** [comment]
>  Also adapt to new gardener API garden.sapcloud.io/v1beta1

The new API is gardener.cloud/v1[alpha|beta]1 :wink:
