### ISSUE TITLE
Copy of kubeconfig fails

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#54]
When I press the copy kubeconfig button in the cluster details view, nothing seems to get copied into my clipboard?

**Comment by vlerenc** [comment]
Cannot reproduce.

**Comment by vlerenc** [comment]
Ah, now I can reproduce it: it only/always happens when I navigate to the seed and the kubeconfig of this seed cannot be copied.

**Comment by PadmaB** [comment]
It also fails on the clusters overview page as shown in the snapshot below.

![image](https://user-images.githubusercontent.com/2491252/38799851-41c6d8b6-4183-11e8-8672-31d5b302c1da.png)

**Comment by petersutter** [comment]
Hi @PadmaB, thanks for reporting. This is a different issue and is fixed with commit 8099fdd7f426f27b34bbe3c485b51b1a6cf819fa
