### ISSUE TITLE
Defer rendering

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#55]
When the displayed clusters receive many events, the rendering clogs the CPU. If possible (limited investment), let's find out whether we can defer the rendering for e.g. 200ms (after the first new event hits the backend).

**Comment by petersutter** [comment]
haven't found a setting on the framework level.
Introduced a new throttling mechanism (for now only for shoots), based on the lodash throttle function https://lodash.com/docs/4.17.5#throttle.

Current wait time defined for the throttling is 1 second, however the first incoming event within this 1 second time window is fired immediately, to keep the UI as snappy as before. 

You can try out the behaviour of the throttling function here by moving the mouse over the trigger area https://codepen.io/psutter/pen/mxNmaO
(forked and slightly modified from codepen published on https://css-tricks.com/debouncing-throttling-explained-examples/)
