### ISSUE TITLE
Project Roles

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#553]
Support Project Roles in Gardener Dashboard, need to support different scenarios

**Comment by vlerenc** [comment]
Can you be a bit more specific which roles are planned and differentiate #476.

So far my understand is:
* We have the owner, technical contact
* We wanted to have the sponsor, billing contact
* We have admins, actually the members accessing the project

In addition, we have operators (Gardener), which are not reflected by project roles. Also, we have some projects with "viewer" role (5 overall in Canary). Where are they coming from and what's the meaning?

If we keep the 3 roles above, Gardener operators remain separate, then:
* Technical contacts should have all permissions, including project members (?) and project administration excluding cost center
* Regular members should have almost all permissions, excluding project members (?) and project administration
* Billing contacts should have limited permissions, i.e. only viewing clusters (especially their metering/billing reports), secrets, members, administration (cost center is the only field they may actually change)

**Comment by grolu** [comment]
Actually this is all related. The first step is to support role management in the Dashboard. As of now, Gardener supports two roles, `admin` and `viewer`. The dashboard currently has no handling to differentiate those. The viewer as fewer rights and is, for example not eligible to create shoots. Trying to do so will lead to an error in the Dashboard - but we should rather disable / hide information and actions for which the user as no permissions. This, along with the ability to manage roles (admin / viewer) is what we are currently working on. 
Regarding #476 - this concept will not work for the dashboard as we need to know all roles and their permissions as we cannot dynamically check for every button etc. if we can show it to the user, we already discussed this with the colleagues. We are waiting for the colleagues to move forward with their efforts regarding user management.
Technical Contacts / Owners will (for now) have no permissions at all, the role is more a label and the owener will need the admin role in addition in order to have any rights in the project. Regarding the `billing` or `metering-viewer` role  - this role will fgrant access to the reports and could be used to create a dashboard view for users without any permission but access to the reports. However, also viewer  and admin roles should get access to those reports, as we need them to show metering information for running clusters to the users of the dashboard.

**Comment by grolu** [comment]
@petersutter, @wyb1 any additions or comments?

**Comment by vlerenc** [comment]
If #476 isn't fitting anymore, then let's close it. As for metering/billing reports, everybody should be able to see them, yes. Yes, the owner has permissions per se. However, when we introduce roles, he will get one (far-reaching). Could you please describe the expected roles and permissions (roughly would be already fine)?

**Comment by grolu** [comment]
As far as I know there will be one additional role built into the Gardener core, which is the `owner` role. However this role has (as of today) no special permissions, but is only used to identify the owner - as preparation for a future deprecation of the `spec.owner` field.
See also https://github.com/gardener/gardener/pull/1948#issuecomment-589513005
