### ISSUE TITLE
No CIDR displayed

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#577]
For gcp clusters (and maybe others?), the CIDR on the cluster details page is not shown.
<img width="313" alt="Screenshot 2020-01-29 at 17 18 43" src="https://user-images.githubusercontent.com/5526658/73375057-87a0c780-42bb-11ea-8600-724022350189.png">

**Comment by petersutter** [comment]
Hi @rfranzke, do you think this field still makes sense to show on the cluster details page? 
Or maybe it makes more sense to display the CIDR ranges of `spec.networking` (pods cidr, services cidr, nodes cidr). WDYT?

**Comment by rfranzke** [comment]
Yes, this makes sense (`.spec.networking`). +1
