### ISSUE TITLE
Seperate shoot info endpoint

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#581]
Currently, with the shoot info endpoint we fetch the kubeconfig from the garden cluster and monitoring / logging credentials from the seed.
For seeds behind a firewall that can't be reached by the dashboard backend the request to the info endpoint takes very long to return because we run in a timeout when trying to talk to the seed kube-apiserver. The consequence is that also the access details (kubconfig) for this cluster is only shown after the timeout.
We should split the info endpoint, so that we have one endpoint to fetch data from the garden cluster and one (for admins) to fetch data from the seed.

**Comment by grolu** [comment]
#550 We also need to solve the not reachable seed issue
