### ISSUE TITLE
Provide Gardener Users with Kubeconfig for the Gardener API

### ISSUE THREAD

**Issue by vpnachev** [gardener/dashboard#586]
The dashboard provides Gardener users with [ID Token](https://github.com/gardener/dashboard/blob/327bcf89d46ab03841309b00e8418856f746acd5/frontend/src/pages/Account.vue#L24-L27) which is valid token for access of the Gardener API.

It would be nice, if the next to the `Copied ID Token to clipboard!` a `Download Personalized Kubeconfig` button is available. Basically, this button can re-use everything from the robot kubeconfigs, it just has to replace the token value and remove the default project namespace from the context.

I think there should be some notification that the personalized kubeconfig is expireable and has to be renewed after some time.

This enhancement will ease end users to use other means to access the API, e.g. `kubectl`, when a robot Service Account cannot be used, e.g to create Projects via kubectl.

PS. A more complicated but robust solution is described here https://github.com/gardener/dashboard/issues/417

**Comment by grolu** [comment]
We hope that we can start working on a robust solution soon, stay tuned. I will close this as we expect to have a solution soon.
