### ISSUE TITLE
Logout does not invalidate the ID Token

### ISSUE THREAD

**Issue by vpnachev** [gardener/dashboard#592]
When I logout from the Gardener Dashboard and then login, I am not challenged to provide my credentials again. It looks the sp initiated logout was not executed.

/kind bug

**Comment by grolu** [comment]
I am able to reproduce this behavior. However, it looks like the ID service is caching your credentials, as the dashboard performs the logout correctly and then redirects to the ID service which immediately performs the login.
@holgerkoser can you please double-check?

**Comment by holgerkoser** [comment]
[dex](https://github.com/dexidp/dex) does not support Single Log Out methods in the SAML connector. https://github.com/dexidp/dex/issues/1600. That is one reason why we should work on an identity solution without dex.
