### ISSUE TITLE
Dashboard fails with members with huge names.

### ISSUE THREAD

**Issue by swilen-iwanow** [gardener/dashboard#594]
How to reproduce: 

1. Create project
2. Add member with size of 15000 chars
3. Try to delete.

What happend: 
Network error: ERR_CONNECTION_CLOSED

**Comment by swilen-iwanow** [comment]
kind/bug

**Comment by vpnachev** [comment]
It looks like the issue here is in the internal API of the dashboard, cause the browsers tries to send a delete request to `https://dashboard/.../<member-name>` which fails.
Project members with such long names are manageable via the `core.gardener.cloud/Project` resource.

**Comment by grolu** [comment]
Moved this to Icebox as we currently have no plans to fix this issue. However, we may change our api to transfer all data as body payload, so I will leave the issue open until we do this or decide against it.

**Comment by grolu** [comment]
Let's close this. No plans / capacity to fix.
