### ISSUE TITLE
General Status Information

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#6]
# Story
- As operator, I want to inform all users about a certain issue (e.g. AWS Europe out of M2 instances; Clusters in Azure North America temporarily down, landscape/URL change) via a banner of sorts in the dashboard (or something similar; UX to be defined), so that I can roll-out important information via this channel.

# Acceptance Criteria
- [ ] Provider/admin can create messages for the dashboard to display
- [ ] Dashboard shows message after login

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
@petersutter @holgerkoser @grolu Can we please increase the importance of this ticket to get our deprecation message out (landscape switch)?

**Comment by petersutter** [comment]
example
![example.png](https://images.zenhubusercontent.com/5a269e418a75884b9089eebb/78f4411b-50c3-4931-9a4f-9d474c805a5c)

**Comment by petersutter** [comment]
usage (add to frontend config):

´´´
frontend:
  alert:
    message: >
      This is a dummy **Markdown** alert message
    type: info
´´´
