### ISSUE TITLE
Usable mass operations on Gardener Clusters UI screen

### ISSUE THREAD

**Issue by Emilius1** [gardener/dashboard#631]
**What would you like to be added**:
As Gardener operator I would like to have some mass usability operations on clusters level so it could save me some time and boost my productivity.
Please see the attached screenshot with a proposals but here are three mass operations as a start:
 - "Hibernate All". It will trigger hibernation of all clusters
 - "Wake Up All". It will wake up all clusters
 - "Clusters Kubeconfigs". It will download/copy a merged kubeconfig file holding configurations to all clusters. So one can add only one file in his kubectl env and be able easily to switch between clusters with "config use-context"
**Why is this needed**:
Usability and boost productivity.
![Gardener_clusters_mass_operation](https://user-images.githubusercontent.com/14806209/76998273-7724d900-695d-11ea-94d3-1993c794b421.png)

**Comment by grolu** [comment]
/close
We currently have no plans or capacity to invest in this feature.
Mass operation should (if at all) be done via command line. [gardenctl](https://github.com/gardener/gardenctl-v2) offers easy access to all shoots. It is also possible to build custom scripts if certain tasks (e.g. wakeup all) shall be performed for a bunch of shoots at once.
