### ISSUE TITLE
Shoot List UX refactoring

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/dashboard#634]
**What would you like to be added**:
I would like to change the ShootList UI to clearly show the status of a Shoot.

**Why is this needed**:
Even though the Gardener Dashboard has not started with the initial purpose to be used by endusers / Shoot owners but rather by an Gardener Operator - it is possible and common practice that Shoot owners also have limited access to their project in the dashboard.
That's why the Dashboard should be catered not only towards the operator, but also towards Shoot owners / endusers. 

**Example**
In the following picture, the Shoot "Status" indicates a green Checkmark. As a Shoot owner I do find that confusing given the fact that the Cluster is completely down (see Readiness). 
![image](https://user-images.githubusercontent.com/33809186/77090617-b4de3c00-6a07-11ea-85bd-4a017c984779.png)
As an enduser I find it not to be evident (even though there is a tooltip when hovering over the icon) that this targets only the reconciliation what is a Gardener internal process and has no direct impact on the availability of the Kubernetes cluster. 

**Goal**
- Enhance / Change the UX of the Dashboard Shoot List so that it is easy for the end-user to check the status of the Shoot (Overall Status, Reconciliation, Availability of the Kubernetes Cluster)

** Concrete Proposal ** 

- Rename the current column "STATUS" to "RECONCILIATION"
- Add the column "Status" that aggregates the information for the Shoot conditions (readiness)
- As an enduser I would also like to see if my Shoot is available - the Kubernetes cluster itself is working. That's why I propose using the term "AVAILABILITY" instead of "READINESS"
-  Move the Kubernetes version column before the status information

Please see the following screenshots:

![image](https://user-images.githubusercontent.com/33809186/77091828-603bc080-6a09-11ea-9a2a-85693587c4ae.png)

![image](https://user-images.githubusercontent.com/33809186/77091921-82cdd980-6a09-11ea-93c2-884dca39bb5b.png)

Shoot shows a "Shoot is healthy" tooltip and a Green Icon if everything is fine (like in the reconciliation).

[Please see the following proposal implementation / draft](url).

**Comment by grolu** [comment]
Hello @danielfoehrKn,
thank you for the issue and also for providing the PR. In general, we understand your requirements and especially your goal to improve usability for end users.
We discussed this internally and we agreed that a column showing the overall _health_ of a cluster could indeed improve the UI. However, we find it difficult to rename the existing columns. While this may help some users to better understand the cluster statuses it might confuse operators. Moreover, the current `Status` column does not only show the `Reconciliation Status` but also other things like:
- Creation / Deletion Progress
- Hibernation Status
- All sorts of errors, not only _reconciliation errors_ but also errors during creation (like invalid credentials) or problems while deleting a cluster

Regarding renaming of the `Readiness` column we also see some issues. Naming it `Availability` suggests that the components which show up ok, are actually reachable which they may not be the case. The column shows the _inner_ status, not the _outer_ one. Therefore `Readiness` still seems to be the right term.

So our suggestion is to add the proposed additional column but call it `Health` as it shows the overall health of a cluster and keep the naming of the other column as it is right now.

But our view on this is only limited, so if others have a different opinion, please comment. @rfranzke, @vlerenc  WDYT?

**Comment by danielfoehrKn** [comment]
Ok ,thanks for the feedback and considering an overall health status.
I think @vlerenc  is sick. Maybe there are also other people besides these two that are interested in that topic.

I think it would help to have a separation between Overall Status, Reconciliation, and Readiness

> Regarding renaming of the Readiness column we also see some issues. Naming it Availability suggests that the components which show up ok, are actually reachable which they may not be the case. The column shows the inner status, not the outer one. Therefore Readiness still seems to be the right term.

What do you mean by inner / outer status? I think I need further explanation on this.

Gardener actually pings these components and checks the Kubernetes object it deployed (reachable, checks conditions, .... ) and the objects the extensions deployed. They are also checked regularly (default: 30 sec) - so we can be quite sure that for components which health check is successful, they are "reachable"and thus available.

In Gardener those checks are called Health Checks. They should reflect the health of the Kubernetes cluster. To make that more tangible I proposed the name availability. 
I would be also fine if it is renamed to "Cluster Health" or similar - but I am asking myself why it is called different in Gardener and in the Dashboard, even though the Dashboard is only collecting this information from the Shoot.

APIServerAvailable
- The Gardenlet makes availability checks against the Shoots API server -> make sure the server is reachable.

EveryNodeReady
-  Retrieve Shoot Kubernetes Nodes and check if they are healthy. The kubelet sends regular heartbeats (if not: node unhealthy)  and we have a node problem detector to check if there is something wrong with the particular K8 node and machine. So if the Node shows up as ready, the node is available and reachable.  

ControlPlaneHealthy
- The Gardenlet performs availability checks against its deployed ControlPlane components (e.g kube-controller-manager) and checks the conditions on the deployment. Also collects the health information from the extensions that themselves make checks on the Kubernetes resources they deploy.

SystemComponentsHealthy 
- Same thing.

>Moreover, the current Status column does not only show the Reconciliation Status but also other things like: 
> 1) Creation / Deletion Progress
> 2) Hibernation Status
> 3) All sorts of errors, not only reconciliation errors but also errors during creation (like invalid credentials) or problems while deleting a cluster

And that mix of information is what I propose to change.
- 2 ) is the logical state of the Cluster,  
- 1 ) and 3 ) are part of reconciliation information as all of this information is coming from the reconcile.

> So our suggestion is to add the proposed additional column but call it Health as it shows the overall health of a cluster and keep the naming of the other column as it is right now.

I do not think that health is the right label here. 
In Gardener terms it is:   Reconciliation information + HealthCheck results

Let me precise the information I would expect in each column:

Status / Overall Status
- Logical state of the cluster
  - Creation / Deletion / Waking Up/ Hibernated / Hibernating / ControlPlane Migration in Process - Indicator.
- Also Indicates if there are errors regarding availability or during the last / current reconciliation
- So it is composed of the logical state of the cluster + problems

Reconciliation
- Show progress of the reconciliation 
- Show what operation the reconciliation is performing
- Show errors that occurred during the last reconcile
- Not: mixed with the Status information 

Availability / Cluster Health / Readiness
- Like today

**Comment by grolu** [comment]
The separation is not reflected in your PR. Could you adapt it to include the things you mentioned in your comment, like moving the creation / deletion / hibernation state to the new status column? Thank you

**Comment by danielfoehrKn** [comment]
Closing this for now as I currently do not have the capacity to work on it. 
Will reopen when I work on it.

**Comment by vlerenc** [comment]
In general I have to agree that our shoot status and conditions (in the shoot resource and their representations in the Dashboard) is not what the people are looking for/expect. You mention this here @danielfoehrKn, @freegroup mentioned it back in #211, some months ago @stephanzlatarev mentioned that as well.

People want one green/red icon and it's also what other managed services offer. That however is problematic as there are indeed multiple aspects, e.g. a failed reconciliation (the column should maybe rather be called last operation as this is what it stands for) doesn't mean the cluster is malfunctioning in any way. The other way around, a green last operation and red conditions may mean that the cluster is completely down. The question is how to visualise that well.

As for the compound status, I am not sure whether we can use `shoot.gardener.cloud/status`/how it is computed @grolu. If it is already what we need, fine. But aren't we filtering out certain triaged errors like invalid credentials? I have forgotten. If it's not the right one, I am not sure we need a new one. Stakeholder automata should deal with our status and conditions. Human users on the other hand work differently and look for the one single icon telling them everything, but if it's not there/green, they have the mental capacity/ability/smarts to find out more, which (unexpecting) automata can't. I believe we should therefore avoid the introduction of a new (programmatic) compound status in the shoot resource (and only think about the UI/Dashboard here). A new status field would otherwise enlarge our API surface and may foster stakeholder automata which start alerting for all kind of non-critical issues.

**Comment by grolu** [comment]
Actually, if I recall this correctly we filter out the user issues on the UI. The status label is set to `unhealthy` for user issues, too. However, it is also `unhealthy` for reconciliation issues, which as @vlerenc mentioned not necessarily mean that the cluster is not working.
Introducing a separate label (or a different status label value) could be an option, definitively better than the Dashboard making assumptions about the cluster health by computing an overall status manually. @rfranzke maybe you can share your opinion, too.
