### ISSUE TITLE
OpenStack: replace "tenant" term with the "project" term

### ISSUE THREAD

**Issue by kayrus** [gardener/dashboard#646]
**What would you like to be added**:

End users get confused by the "Tenant" name on add credentials modal window. OpenStack used this term long time ago and it must be changed to a "project"

**Why is this needed**:

It's quiet frequent confusion on the user end.

/cc @grolu  @rfranzke

**Comment by rfranzke** [comment]
What about putting both ("project or tenant")?

**Comment by kayrus** [comment]
@rfranzke tenant term is deprecated long time ago.

**Comment by rfranzke** [comment]
Yes, but the OpenStack secrets still take `tenantName` only: https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/internal/credentials.go#L29-L35
https://github.com/gardener/gardener-extension-provider-openstack/issues/3 is still open

**Comment by kayrus** [comment]
@rfranzke well, at least it is not visible for the end user. BTW, gophercloud automatically transforms tenant to project for keystone v3.

**Comment by petersutter** [comment]
@kayrus @rfranzke 
"project" or "project or tenant"?

**Comment by kayrus** [comment]
I'd not use "tenant" at all to avoid any confusions.

**Comment by rfranzke** [comment]
I'd still would vote for both, mainly be cause above mentioned issue is still open. Yes, it's transparent for the user in the dashboard, but if he takes a look at the created `Secret` via a robot serviceaccount later on then he might wonder where the project information is (yes, it's quite obvious and not difficult to sort out; still, more consistent imo).
Anyways, that's just my personal opinion, I don't care too much. Do whatever you prefer.

**Comment by grolu** [comment]
We cannot decide this. Can someone from the Open Stack experts comment on this?
@dkistner @mandelsoft @MartinWeindel

**Comment by dkistner** [comment]
I would also vote for use a combination of both term in this order `project / tenant`.
We can remove tenant term again when the mentioned issue is completed.

**Comment by grolu** [comment]
Thank you for your feedback. I will rename the field to `Project / Tenant Name`
