### ISSUE TITLE
Shoot name length restriction

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#650]
We have an enhancement request from a dashboard consumer:

**What would you like to be added**/**Why is this needed**::
We have a lot of shoots in our projects and sometimes 10 characters are just not enough to give them a meaningful name. Would you consider adding some "Display Name"?
Alternatively, it would be cool, if I could select a custom-label in the "Column Selection" of the dashboard.

**Comment by petersutter** [comment]
First of all we should improve the validation in the dashboard. Currently the restriction is:
- Project name max length: 10 characters
- Shoot name max length: 10 characters

But actually the limitation is: the sum of both must be <= 22

**Comment by grolu** [comment]
We could also make the shoot name length dynamic, depending on the length of the project

**Comment by petersutter** [comment]
yes I guess we should first start with that

**Comment by grolu** [comment]
Added PR for the cluster name length, split other topic into separate issue: https://github.com/gardener/dashboard/issues/686
