### ISSUE TITLE
User journals / issues

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#651]
**What would you like to be added**:
In case of issues with a cluster, users usually contact the gardener operators via mail/slack or other means.
The dashboard should give the users the possibility to create issues for their cluster, similar to the journal feature.

**Why is this needed**:
This gives users and operators a better overview of the created issues.

**Comment by vlerenc** [comment]
Indeed, let's allow all users (not only ops) to create general tickets (via the (?) at the top) and cluster issues (where we have the journal issues).
