### ISSUE TITLE
Namespace missing in YAML representation of Create Cluster dialog

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#653]
**What happened**:
The `.metadata.namespace` is missing in YAML representation of Create Cluster dialog.

**What you expected to happen**:
The namespace is present.

**How to reproduce it (as minimally and precisely as possible)**:
Open the create cluster dialog and navigate to the YAML tab.

**Comment by grolu** [comment]
You are right, we discussed this some time ago. It works because we create the resource inside the namespace, however we should add it to the spec. I will take care of it.
