### ISSUE TITLE
Used secrets can be deleted without notice

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#66]
It is possible to delete a secret which is used by a cluster. The label with the notice that 
the secrets is used by "n" clusters is missing. Additional the delete button is active.

## expected behaviour

<img width="992" alt="bildschirmfoto 2018-04-24 um 10 13 33" src="https://user-images.githubusercontent.com/1155039/39174562-5ce33d58-47a8-11e8-86e3-df9ba1ba64c9.png">

## current behaviour
<img width="1378" alt="bildschirmfoto 2018-04-24 um 10 06 34" src="https://user-images.githubusercontent.com/1155039/39174575-661d8068-47a8-11e8-99cc-85712ac9c2aa.png">
<img width="865" alt="bildschirmfoto 2018-04-24 um 10 06 53" src="https://user-images.githubusercontent.com/1155039/39174595-79788004-47a8-11e8-8d56-2ace9e255e38.png">

**Comment by petersutter** [comment]
regression introduced with garden dashboard version 1.11.0 commit a5d7764b210b6024e440ae1d6e459e90865273e4
