### ISSUE TITLE
Improved Maintenance Time Window Info

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#67]
At the moment the dialog looks as if the maintenance takes place every day at this time of day. But if I understood correctly, then this is the allowed time window if an update is necessary.

Possibly you can present a text to the user that explains this a little more clearly

## Suggestion
instead placing the message at the bottom of the dialog it could stay at top of the form.

<img width="1280" alt="bildschirmfoto 2018-04-24 um 10 34 34" src="https://user-images.githubusercontent.com/1155039/39175977-ef057478-47ab-11e8-925e-b94b355081e7.png">

**Comment by vlerenc** [comment]
A bit lengthy, isn't it?

How about "Maintenance Start Time* (respected by automated updates when available)"

**Comment by freegroup** [comment]
lengthy? maybe. But sometimes you have to decide to write down certain things in detail or to tell people over and over again.

**Comment by vlerenc** [comment]
OK, lets' improve the hints then (in whatever form you see fit: always visible text, pop-ups, whatever fits the/your Dashboard UX concept best):
- In general/maintenance start time: Provide start of maintenance time window in which Gardener may schedule automated cluster updates.
- Operating System: Update the operating system of the workers (requires rolling update of all workers, ensure proper pod disruption budgets to ensure availability of your workload)
- Kubernetes Patches: Update the control plane and restart the workers (control plane, most notably the API server will be briefly unavailable during switch-over)

**Comment by vlerenc** [comment]
@rfranzke Would you agree to the above text? It's not perfect, but considering the space and unclear knowledge the reader may or may not have, it seems an "acceptable simplification" of the actual process?

**Comment by vlerenc** [comment]
Thanks @grolu. When trying it out, I noticed a tiny rendering issue:
![Screen Shot 2018-06-29 at 15.33.13.png](https://images.zenhubusercontent.com/5a57377f4b5806bc2bc254ee/f3a46698-4a26-470b-a6a4-f28a733145ba)

**Comment by grolu** [comment]
This seems to be an issue with smaller browser window sizes. I will have a look why the control does not use the full width.

**Comment by grolu** [comment]
@vlerenc Text now uses full window width. However, if the window size is too small, the text still gets truncated. But this seems ok from my point of view.

**Comment by vlerenc** [comment]
Sure, thanks.
