### ISSUE TITLE
Disabled actions for `PROD`clusters

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#671]
To protect critical parts of the Gardener landscape (e.g. seeds), we disabled all modifying actions in the dashboard. This includes the YAML editor which we put into read-only mode.
However, this can be changed. Let's briefly discuss if the current implementation makes sense or if we should loosen rules here.

**Comment by vlerenc** [comment]
And the outcome was? Closed. ;-)

**Comment by grolu** [comment]
As no one reacted, I assumed that the question has already been answered - it is not an error but works as designed and there is no need to change the behavior.
