### ISSUE TITLE
Double-clicking cluster name in deletion dialog (possibly also others) selects the word "cluster" as well

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#679]
**What happened**:
<img width="618" alt="Screenshot 2020-04-27 at 12 31 12" src="https://user-images.githubusercontent.com/4974203/80362614-38027580-8883-11ea-84ee-6db1858a6727.png">

**What you expected to happen**:
Double-clicking only selects the cluster name as it was the case in the past, I believe.

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot.

**Environment**:
Mac/Chrome.

**Comment by petersutter** [comment]
Issue was introduced with the vuetify upgrade
