### ISSUE TITLE
provide link to send email to all project members

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#68]
It would be fine if we can send an email to all project members. The link should contain
all project members as "to" and my own email as "cc".

the label of the link could be **members@&lt;PROJECTNAME&gt;**

<img width="898" alt="bildschirmfoto 2018-04-24 um 10 46 44" src="https://user-images.githubusercontent.com/1155039/39176452-2821954c-47ad-11e8-9ada-7ee85184ab2a.png">

**Comment by grolu** [comment]
@freegroup I had a short chat with @vlerenc. We could easily build this, however we do not want to overload the UI with unnecessary functionality. Is this a request that you get from your stakeholders? Could you elaborate a bit how this functionality would help. Is this a scenario that happens regularly?

**Comment by grolu** [comment]
@freegroup Could you please explain for which scenario this feature is useful? Otherwise I will close this issue.

**Comment by freegroup** [comment]
for team communication. 

For some reasons, we are using the technical user to create a cluster. Sometimes a cluster looks orphaned and we send an email to all projects members and ask if we can delete the cluster.
This happens a lot if you have a broken CI/CD landscape and some of the clusters didn'T cleanup up by the pipeline.

At the moment we build our mailing list by hand. But if you have a bigger team setup this could help.

**Comment by grolu** [comment]
Currently on hold until we handle user data properly
