### ISSUE TITLE
Dashboard search to index as well shoot clusters' YAML config along with name

### ISSUE THREAD

**Issue by evilyeti** [gardener/dashboard#683]
**What would you like to be added**:
Search in Gardener dashboard to also index the YAML files of the shoot clusters in search index, including both successfully created, as well as failed clusters. 

**Why is this needed**:
Right now search only indexes cluster name. In projects, which have a high number of shoot clusters, it would be very practical to be able to search and filter them by custom fields in the YAML config. The alternative approach today would be to click cluster by cluster.

**Comment by grolu** [comment]
@petersutter @holgerkoser This is a very difficult thing to achieve, also in terms of performance. Moreover, it could be difficult to make this a valuable feature, in terms of returning valid results.

@evilyeti please have a look at https://github.com/gardener/dashboard/issues/686 - maybe this solves (part) of your request?

**Comment by grolu** [comment]
I close this issue as with the custom shoot fields feature (https://github.com/gardener/dashboard/pull/890) it is possible to expose arbitrary fields and make them searchable.
