### ISSUE TITLE
Define Custom Labels for Shoot Overview

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#686]
Define custom labels / annotations for the dashboard that are rendered as optional column in the shoot overview. This feature can help organizing clusters.

**Comment by phil9909** [comment]
Any progress on this? Would be really helpful

**Comment by grolu** [comment]
Thank you for your feedback. We talked about this internally and have the following proposal:
A project administrator can define custom, project specific fields as an annotation on the project resource. This could look like this:

```
dashboard.gardener.cloud/customField : {
	path: [String] path in shoot spec, can be existing field or custom annotation / label
	name: [String] Name of the custom field
	showColumn: [Bool] Field shall appear as column in the cluster list
	columnSlectedByDefault: [Bool] Field shall be selected by default on the cluster list (not hidden by default)
	showDetails: [Bool] Field shall appear in a dedicated card (Project specific fields) on the cluster details page
	icon: [String] mdi icon for field on the cluster details page
}
```

In the first implementation we will support those fields on the project cluster list, but not on the _all projects_ list. We could support this and offer a filter like `hide custom fields` which is hidden for operators by default. However as this requires some effort we decided to move this to extended scope.

Please give me feedback if this goes into the right direction and fulfills your requirements.

**Comment by phil9909** [comment]
Your proposal sounds promising and seems to cover our use-case. Just two things:
1. The proposed annotation is called `dashboard.gardener.cloud/customField` and as far as I'm concerned one can not create two annotations with the same name. I would hope you will support more than one customField per project. So you could
   - call it `dashboard.gardener.cloud/customFields` and instead accept an array of the struct you proposed.
   - use `custom-fields.dashboard.gardener.cloud/[name]`
1. There is a typo in `columnSlectedByDefault` 

Thanks a lot

**Comment by grolu** [comment]
Yes you are right of course - we planned to have this as an array. I corrected the things above.
