### ISSUE TITLE
Show Mailing List Information

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#7]
# Story
- As user, I want to easily reach the Gardener dev/ops teams or like-minded folks, so that I can engage in a communication with them or get help from them (or others).
- As provider, I want to establish a communication channel for everybody, so that I learn of issues (fast) and also foster a community that can help and support itself.

# Acceptance Criteria
- [ ] Show link to our mailing list https://listserv.sap.corp/mailman/listinfo/kubernetes-users in the UI
- [ ] Show "compose message" button/link that opens the default e-mail client accordingly (mailto:kubernetes-users@listserv.sap.corp)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?

**Comment by petersutter** [comment]
Added compose message button in internal garden-setup project (commit 1ab8d159872bc95389c99ed9164fb0b8db2bd64e).
Regarding the link to the mailing list: we already have a "feedback" link that points to the feedback page of our landing page that also has a link to the mailing list.
