### ISSUE TITLE
Run chart tests during ci/cd build

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#706]
**What would you like to be added**:
Currently the chart tests are not run automatically. Instead, they should be run during ci/cd build.

**Why is this needed**:

**Comment by holgerkoser** [comment]
In order to run chart tests we need to install the helm binary in the `builder` image. This could be done like in the [alpine-docker](https://github.com/alpine-docker/helm/blob/master/Dockerfile) image.

**Comment by grolu** [comment]
In an internal discussion we agreed that we do not include the helm chart tests in the build pipeline as it is additional overhead without real value: If someone modifies the helm charts one would always execute the helm charts manually. As we do not modify charts that often we can ensure this.
