### ISSUE TITLE
gTkn cookie is too large

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#720]
**What happened**:
The JWE encryption we use for the gTkn cookie value quickly runs out of space (max. 4096). It would be better to use a more compact format.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by grolu** [comment]
Encryption cannot be made significantly smaller. If we get too many groups, we cannot store it in a cookie. But for now we can leave it as is.

**Comment by petersutter** [comment]
Backend session storage with a slim session ID cookie is likely the path forward here - it would eliminate the size constraint entirely regardless of token payload or encryption overhead.
