### ISSUE TITLE
Display stale information on project

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#721]
**What would you like to be added**:
Projects that are not actively used for a certain amount of time are marked as stale. This information should be displayed on the UI.
See also https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md#project-controller for more details

**Why is this needed**:
So that a user is informed before a project is cleaned up.

Related gardener PR https://github.com/gardener/gardener/pull/2446

**Comment by grolu** [comment]
See also https://github.com/gardener/gardener/issues/1997
