### ISSUE TITLE
Slack Integration via Bot

### ISSUE THREAD

**Issue by vasu1124** [gardener/dashboard#73]
# Story
- As DevOps team responsible for workloads running within clusters (not the Gardener operators), we use Slack to coordinate Dev & Prod activities connected to multiple clusters. Gardener should have a Bot connectable to configurable slack channels, such that certain alerts and events are (pre-)announced in such channels (multiple clusters one channel or one cluster one channel. no multiplexing to multiple channels).
- The Bot should also offer a subset of commands to configure its behaviour, e.g. subscribe to workload specific events.

# Motivation
Help ease & coordinate the work of our customers development & operator teams.

# Acceptance Criteria
- [ ] From the cluster details the cluster owners can configure a Bot to report into a slack channel (bi-directional confirmation)
- [ ] All existing high-prio alerts and a subset of events for a cluster are reported to the slack channel.
- [ ] Bot offers subset of commands (e.g. to ignore or quiesce) to configure its behavior and subscribe to workload specific events (e.g. with regexp).

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
Wouldn't you agree that this level of integration goes beyond the scope of Gardener and Dashboard and should be an independent component. We for instance have a Slack integration already, but via the monitoring stack, alert manager and a Slack receiver. As for cluster operations, a separate controller seems cleaner. I will therefore close this ticket.
