### ISSUE TITLE
Show warning when changing worker group name

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#732]
**What would you like to be added**:
A warning should be displayed when changing the name of a worker group.

**Why is this needed**:
The user must be informed that the nodes will be recreated and that this operation will result in a downtime of the workload running on the affected nodes.

**Comment by danielfoehrKn** [comment]
> The user must be informed that the nodes will be recreated 
It rather means that the worker pool with <old-name> is being deleted and a new worker pool is being created.  That is different from a rolling update of an existing worker pool.

I think that a deletion 
-  also drains the nodes (like a rolling update)
- but drains all nodes at the same time -> its not a rolling update

> will result in a downtime of the workload running on the affected nodes

This happens only if the nodes of the new worker pool have not joined yet and the nodes of the old worker pool are already drained. This also indicates missing PDBs.
