### ISSUE TITLE
No clusters in incognito mode

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#74]
When I open the Dashboard in incognito mode, I see errors about the websocket connection in the log and get no clusters in the UI.

**Comment by petersutter** [comment]
could you add a screenshot? I just checked it in incognito mode and it was working fine

**Comment by vlerenc** [comment]
Just from afar (no VPN access right now), @holgerkoser saw it in a screen sharing session.

**Comment by grolu** [comment]
Close this issue for now as we cannot reproduce the issue.
