### ISSUE TITLE
Blank screen when logging in with an obsolete or invalid link

### ISSUE THREAD

**Issue by vasu1124** [gardener/dashboard#740]
**What happened**:
click on any link *other* than <gardener landscape>/namespace/garden-project/shoots/ , e.g.
<gardener landscape>/namespace/garden-project or
<gardener landscape>/xyz

Received a blank page.

**What you expected to happen**:
Error Page with link to default page

**Comment by petersutter** [comment]
Hi @vasu1124 yes we currently lack proper error handling in this regards, we also have an issue for this
https://github.com/gardener/dashboard/issues/316

/duplicate

**Comment by petersutter** [comment]
FYI, will be fixed with https://github.com/gardener/dashboard/pull/744
