### ISSUE TITLE
Factor out terminal bootstrapping

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#748]
**What would you like to be added**:
The code related to the terminal bootstrapping should be factored out of the dashboard and a new component should be created that takes over this task.

**Why is this needed**:
This is one step in the direction to be able to scale up the dashboard with multiple instances.

**Comment by petersutter** [comment]
With this we can also get rid of the terminal bootstrapping related permissions https://github.com/gardener/dashboard/blob/79703af3a66ffbbd693d7aa941bf65ac7e3804a7/charts/gardener-dashboard/charts/application/templates/clusterrole.yaml#L63-L88 in the dashboard helm chart

**Comment by grolu** [comment]
Completed with https://github.com/gardener/dashboard/pull/1383
