### ISSUE TITLE
Region labels in Gardener didn't match the display names in AWS Console.

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#75]
sometimes the user must map the region labels used in the Gardener to the correponding AWS labels used to create a ticket to increase some infrastruc. limit like elastic IP,...

example screenshot
<img width="2010" alt="bildschirmfoto 2018-04-30 um 14 18 41" src="https://user-images.githubusercontent.com/1155039/39427373-c7134cba-4c83-11e8-8838-6f13f881f79b.png">

In this case it is always neccessary to google them to find the correct region on the
AWS UI. Maybe it is possible to provide a tooltip in the Gardener with the corresponding
AWS naming.

| AWS Regio Labels | Gardener Label |
|-----------------------|------------------------------|
USA Ost (Ohio) |	us-east-2	
USA Ost (Nord-Virginia)	| us-east-1	
USA West (Nordkalifornien)|	us-west-1
USA West (Oregon)|	us-west-2	
Asien-Pazifik (Tokio)|	ap-northeast-1	
Asien-Pazifik (Seoul)|	ap-northeast-2	
Asia Pacific (Osaka-Local)|	ap-northeast-3	
Asien-Pazifik (Mumbai)	|ap-south-1	
Asien-Pazifik (Singapur)|	ap-southeast-1	
Asien-Pazifik (Sydney)	|ap-southeast-2	
Kanada (Zentral)|	ca-central-1
China (Peking)|	cn-north-1	
China (Ningxia)|	cn-northwest-1
EU (Frankfurt)|	eu-central-1
EU (Irland)	|eu-west-1	
EU (London)|	eu-west-2	
EU (Paris)|	eu-west-3	
Südamerika (São Paulo)	|sa-east-1

**Comment by vlerenc** [comment]
We use the official technical names and while I agree that it's a mess, it's not ours and to fix it we would have to jump through too many hoops (the Dashboard doesn't know of the regions and sees them in transit managed by the Gardener which cares for the technical names), so let me please close this ticket. Too much effort for a border case (one or two clusters are usually fine - only if you have more you must raise the quotas), that we are not responsible for and would have a hard time fixing in a clean way (avoiding a dashboard-local mapping table).

**Comment by freegroup** [comment]
👎

**Comment by vlerenc** [comment]
Fair enough.
