### ISSUE TITLE
Authenticate called twice in some cases

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#750]
**What happened**:

July 28th 2020, 09:28:37.872 | 2020-07-28 07:28:37.872 error: Socket /tickets#kuO-2MVwqsbW_tGnAAOs authentication failed: "Cannot redefine property: client"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
@holgerkoser is this issue still present?

**Comment by holgerkoser** [comment]
> @holgerkoser is this issue still present?

Yes. But I think it only occurs in the local development scenario.

**Comment by petersutter** [comment]
> > @holgerkoser is this issue still present?
> 
> Yes. But I think it only occurs in the local development scenario.

I just checked and this issue does not occur anymore
