### ISSUE TITLE
Support OpenStack DNS secrets

### ISSUE THREAD

**Issue by timuthy** [gardener/dashboard#769]
The dashboard allows users to manage OpenStack provider specific secrets which essentially contain re-useable information for [DNS providers](https://github.com/gardener/documentation/blob/df19903e0541ef65fe668071ce8e44fefba8d5cd/website/documentation/guides/administer_shoots/dns_providers/_index.md), except for one missing field [OS_AUTH_URL](https://github.com/gardener/external-dns-management/blob/bc180d53b8bb74f44549cbb647e41dfcc18b6467/examples/20-secret-openstack-credentials.yaml#L11).

For shoot clusters this field is configured in the corresponding `CloudProfile` but unfortunately the same can't be applied when Gardener creates DNS providers.

Therefore, it'd be nice if the dashboard could show an additional field `Auth URL` when users create/manage an OpenStack cloud provider secret. This field is ideally pre-filled with the URL which can be found in the referenced cloud profile so that users don't have to bother about finding this landscape specific information.

/cc @MartinWeindel @mandelsoft @vasu1124 

see https://github.com/gardener/external-dns-management/issues/108

**Comment by MartinWeindel** [comment]
There is also another issue in this context from @mandelsoft (Support configuration of DNS provider secrets  #616)
