### ISSUE TITLE
Dashboard requires restarts

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#78]
We have noticed twice, that the dashboard stopped working. The browser showed 503. After we couldn't identify anything odd, we simply deleted the pod and after it came up again everything  worked again. This happened again 2 days later. Logs from first event were sent out-of-band due to size.

**Comment by PadmaB** [comment]
I am unable to access the dashboard on dev landscape - console shows 503. Maybe this is related to the same issue.
