### ISSUE TITLE
Add button to re-trigger failed operations

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#79]
When the Gardener does no longer retry an operation it sets the `.status.lastOperation.state` of the respective Shoot cluster to `Failed`.
Currently, the dashboard does not allow to re-trigger the Gardener to start the operation again.

Please show a button in the dashboard for those failed clusters which a user may click to make the Gardener start reconciling the cluster again.
Technically, the button should set an annotation `shoot.garden.sapcloud.io/operation=retry` on the Shoot.

**Comment by vlerenc** [comment]
Isn't that a duplicate of #45? Can you please merge both tickets into one, if that's the case? Thanks in advance, Vedran

**Comment by rfranzke** [comment]
Thanks, didn't see that. Merged my comments into #45.
