### ISSUE TITLE
Ops Collaboration Platform

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/dashboard#8]
# Stories
* As operator I want to influence how my clusters and inner entities (like pods and more) are rendered, so that my team and I can work with higher-level abstractions.
* As operator I want to annotate my clusters and inner entities, so that my team colleagues can see these annotations around the world and clock (see also #5).
* As operator I want to add additional information in an easy syntax like a wiki markup language (e.g. md), so that I can collaborate with my team colleagues. 
* As operator I want an integrated ticket system, so that I can create, see and work on issues in my area of work within the same ops tool that I daily use to do my work. 

# Motivation
Gardener shall not only become the technical means to operate Kubernetes clusters, but also a collaboration platform. Some of the above ideas were proposed by @vasu1124, while others were driven by others like the operators (of the week) (e.g. #5).

# Acceptance Criteria
- [ ] Users can influence the rendering of clusters and inner entities (like pods and more) in a wiki markup language (e.g. md) that supports higher-level constructs such as loops (Gardener-flavored markdown)
- [ ] Users can add instance-specific annotations in this wiki-like system and even entire new pages relative to the resource tree (starting at their namespace, then clusters, then the inner entities)
- [ ] Users can create, process, and resolve/close tickets associated with entities in this resource tree

# Implementation Proposal
Replace hard-coded visualisations of clusters and inner entities (like pods and more) and lists of the same with a wiki engine and render templates we store as third party resources in the Garden cluster. Add a ticketing system.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
Actually, #38 already resolves two thirds of this ticket. Putting this ticket on ice for now.

**Comment by vlerenc** [comment]
I guess, not realistic. Closing unless there are objections.
