### ISSUE TITLE
Wrong cluster list after switching project 

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#800]
**What happened**:
If you are on the cluster details screen and switch to different project the selected cluster will be shown as part of the new project list.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
This issue does not occur on any of the released dashboard versions and only occurs for the 1.46.0-dev version
