### ISSUE TITLE
Disable zone removal for AWS clusters

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#805]
> Error occurred: Could not save worker configuration
admission webhook "validation.aws.provider.extensions.gardener.cloud" denied the request: networks.zones: Forbidden: removing zones is not allowed

Currently for AWS Shoot removing zone from .spec.provider.infrastructureConfig is not allowed (not supported).

**Comment by grolu** [comment]
It should be disabled for all infra structures. I'm confused... just rechecked it is disabled for me
