### ISSUE TITLE
Cluster journal is not shown completely

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#82]
I was doing ops, saw a journal comment and notified the owner as suggested there, but when I tried to edit it, I saw that others have done that already, but the dashboard failed to show the consecutive comments. In the dashboard I only saw the very first comment. See screenshots:
<img width="772" alt="screen shot 2018-05-09 at 19 02 39" src="https://user-images.githubusercontent.com/4974203/39828598-f3fceb2a-53bb-11e8-9c1d-8340903aefa4.png">
...but...
<img width="706" alt="screen shot 2018-05-09 at 19 06 51" src="https://user-images.githubusercontent.com/4974203/39828670-2e92f748-53bc-11e8-97df-8d17f03f3814.png">

**Comment by petersutter** [comment]
reopen: need to add better error handling (UI)
