### ISSUE TITLE
Sort preferences are no longer persisted

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#828]
**What happened**:
Sort preferences are no longer persisted.

**What you expected to happen**:
Sort preferences to be persisted as I don't want to sort them every time I open the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open a dashboard

2. Sort the Shoots by for example the infrastructure column

3. Refresh the dashboard and ensure that the sort preference is cleaned up.

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
I just checked, this issue only occurs with the current changes on the `master` branch and not with the currently released dashboard version
