### ISSUE TITLE
Secret Link

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#83]
It would be great, if I could jump directly to a secret when in cluster overview:
<img width="813" alt="screen shot 2018-05-09 at 19 25 21" src="https://user-images.githubusercontent.com/4974203/39829452-cc14ac4e-53be-11e8-9a2f-44822e4ab8d4.png">

**Comment by petersutter** [comment]
where should this link point to? Currently we don't have a "display" view of a specific secret. 
We could link to the secrets page or we could open the "edit" view of this secret.

**Comment by vlerenc** [comment]
Right, good point. At least the secrets page and if we have only edit, then the edit view on top, if possible.
