### ISSUE TITLE
Garden Cluster Kubeconfig Download for Human and Technical Users

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#85]
Can we please offer an option to download the Garden cluster `kubeconfig` for human and technical users and show the latter in the UI. This way, our human users could realise the following flow to help themselves/create and use technical users:]
- Human user downloads his personal `kubeconfig`
- Human user creates service account (a.k.a. technical user) in the Garden cluster with the `kubeconfig` from above
- Human user downloads technical user `kubeconfig` for automation processes

**Comment by mvladev** [comment]
`ServiceAccounts` are not meant for end-users (humans). Can we keep the `Service Account` name and emphasis that they should **only** be used for services?

End-user authentication should only happen via `OpenID Connect Tokens` / `Webhook Token Authentication` as k8s certificates **cannot be revoked**

**Comment by vlerenc** [comment]
> ServiceAccounts are not meant for end-users (humans)

Yes, the purpose is to use them for programmatic access.

> Can we keep the Service Account name and emphasis that they should only be used for services?

What do you suggest?

**Comment by vlerenc** [comment]
We will go for the more integrated/convenient solution and offer a button to create a service account/technical user right away and not offer the download of the (anyways only temporarily valid) human user kubeconfig. Only the service account/technical user kubeconfig can be downloaded. The service accounts/technical users will be shown in a separate section on the members page.

**Comment by holgerkoser** [comment]
It is possible now with commit #70fd05c159bafa28c6893dfbb095444817e0ee11

**Comment by petersutter** [comment]
example screens
<img width="1110" alt="screen shot 2018-07-05 at 22 04 59" src="https://user-images.githubusercontent.com/5526658/42345512-d8c30784-809f-11e8-8758-597598577598.png">
<img width="1110" alt="screen shot 2018-07-05 at 22 07 14" src="https://user-images.githubusercontent.com/5526658/42345516-df380254-809f-11e8-90b3-19d3b8f168c2.png">
