### ISSUE TITLE
Re-login on expired sesion does not navigate to the last page

### ISSUE THREAD

**Issue by vpnachev** [gardener/dashboard#865]
**What happened**:
My session has expired and I was logged out. Before this I was on https://dashboard.example.com/namespace/_all/shoots/, but after I log in I was redirected to my "home" page, in my case it is https://dashboard.example.com/namespace/garden/shoots

**What you expected to happen**:
To be re-directed to the last page on re-loging.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
Dashboard Version: 1.46.1
Browser: Firefox 82.0 on Ubuntu 18.04

**Comment by grolu** [comment]
Will fix this in https://github.com/gardener/dashboard/issues/976

**Comment by grolu** [comment]
/close
This as already been fixed
