### ISSUE TITLE
Make colors configurable

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#873]
**What would you like to be added**:
Make colors of the Dashboard configurable.
To achieve this, a first step is to remove all hard coded color values and color names (such as `cyan darken-2` or `red`) and use `primary` or `error` color variables instead. These variables can be centrally overwritten by configuration.

**Why is this needed**
This is needed to adapt the styling of the Dashboard to various environments / brandings.

**Comment by valentinvieriu** [comment]
How about going the [Tailwind](https://tailwindcss.com/docs/customizing-colors) approach? Use and utility first approach, and name the color universal, and then allow the overwrite via ConfigMap and map Volume approach the utility.css file. In this way they can configure the colors, but also fonts and sizes, even mobile behaviour if they would like.

Using the Tailwind classes might be a benefit, as this is a quite popular library at this moment.

**Comment by grolu** [comment]
Exactly, we are currently working through the code to make use of Vuetify themes (https://vuetifyjs.com/en/features/theme/) instead of hard coded colors in the components. These values can then be overwritten by configuration. Also, this is a step towards dark mode support https://github.com/gardener/dashboard/issues/714
