### ISSUE TITLE
Dashboard Theming

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#875]
This is an ☔ - Issue for all things regarding styling of the Dashboard.

We want to support basic theming / styling of the Dashboard without the need to fork it.
The following (incomplete) list show things that we plan to do
- [x] Make colors configurable (https://github.com/gardener/dashboard/issues/873)
- [ ] Make logos configurable  (https://github.com/gardener/dashboard/issues/874)

This issue can be seen as somewhat related to https://github.com/gardener/dashboard/issues/554

**Comment by valentinvieriu** [comment]
See my suggestion maybe for https://github.com/gardener/dashboard/issues/873#issuecomment-728809734. Theming can be done outside of the build process so Docker images can be reused and maybe just overwritten via config maps at deploy time?
