### ISSUE TITLE
Auto-Close Journal Tickets/Logs of Terminated Clusters

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#88]
When an operator opens a journal on a cluster that later gets deleted (often the case with wrong credentials), the issue in GitHub remains open. The dashboard has no hook into cluster deletion, but it's the instance that created the issue in the first place. What shall we do to auto-close these issues?

I would prefer a shot-term mitigation for now (let's do it from the Dashboard) as we anyways don't know what we will do with the journal down the road. It's super helpful as it is, so I would just go on, learn on the way and we can take a different turn in half a year, but for now I would prefer to only improve, but not refactor it too much. What do you say?

**Comment by vlerenc** [comment]
Thanks, I guess that's OK: if the Dashboard backend isn't up when the shoot gets deleted, it would remain open, I guess, but that's OK.

As for the second part, well, a comment would still be nice.

**Comment by petersutter** [comment]
OK

Yes correct it would remain open.
