### ISSUE TITLE
All Projects when selected shows no content - and it is confusing

### ISSUE THREAD

**Issue by valentinvieriu** [gardener/dashboard#886]
**What happened**:

I've selected All Projects from the left menu, and then I see an empty screen
![image](https://user-images.githubusercontent.com/478866/99370824-719ddb00-28be-11eb-88cc-2b045bfac6a2.png)

I do have 2 projects in my account.
![image](https://user-images.githubusercontent.com/478866/99371361-191b0d80-28bf-11eb-9839-482762ec8c12.png)

**What you expected to happen**:
I don't really know what All Projects should show, I assume a list of all my projects that are available on my account. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
This view is confusing, as it seem to look like I could create clusters. It is hard to understand what is the purpose of this menu, with this current implementation.

**Comment by petersutter** [comment]
This screen is mainly for having an overview of all the unhealthy clusters. This is also indicated in the toolbar of the table. 
<img width="257" alt="Screenshot 2020-11-17 at 10 28 03" src="https://user-images.githubusercontent.com/5526658/99371754-99417300-28bf-11eb-8836-c0d32c447921.png">

If you want to see all the clusters of all your projects you can change the table filter when clicking on the three dots at the right of the toolbar and uncheck the option `Show only clusters with issues`.

**Comment by petersutter** [comment]
By the way, the filter is currently not stored. This will change with this PR https://github.com/gardener/dashboard/pull/884 which is coming with the next dashboard version.

**Comment by valentinvieriu** [comment]
> This screen is mainly for having an overview of all the unhealthy clusters. This is also indicated in the toolbar of the table.
> <img alt="Screenshot 2020-11-17 at 10 28 03" width="257" src="https://user-images.githubusercontent.com/5526658/99371754-99417300-28bf-11eb-8836-c0d32c447921.png">
> 
> If you want to see all the clusters of all your projects you can change the table filter when clicking on the three dots at the right of the toolbar and uncheck the option `Show only clusters with issues`.

This part was not so obvious to me. Now that you've mention it I see it. Did I enabled that filter? Or it was enabled by default?
I would not want this ( as a user of the app ) the filter to be enabled by default.

**Comment by petersutter** [comment]
Yes it was enabled by default.

The main purpose of this screen was for the gardener landscape operators, to have an overview of all the unhealthy clusters. For this use case the filter should be enabled by default.
For non-landscape-operators we could change the default so that all shoots are shown by default. wdyt @holgerkoser @grolu

**Comment by valentinvieriu** [comment]
I will close this as it seems it is not a bug. Would be preferable that the filter is not enabled by default, or maybe some ui needs to be adapted to somehow show this. At this moment having the filter inside of the column selection is not that intuitive, and very hard to see what filter is active or not.
![image](https://user-images.githubusercontent.com/478866/99375668-4918df80-28c4-11eb-9795-cc26005ba2d9.png)
Maybe this can be a more a feature request related to the UI of the filters. I've had a hard time realising that I've had a filter enabled
Thank you

**Comment by grolu** [comment]
@petersutter can you include the changed filter default in #884

**Comment by petersutter** [comment]
yes I will change the default for non-admins
