### ISSUE TITLE
Closing the Warning box it's not remembered

### ISSUE THREAD

**Issue by valentinvieriu** [gardener/dashboard#887]
**What happened**:
I'm closing this alert box on every login, and still pops up.
![image](https://user-images.githubusercontent.com/478866/99373637-ee7e8400-28c1-11eb-9e53-53c71d2db35d.png)

**What you expected to happen**:
I would expect that my action is remembered, and no alert is shown next login

**How to reproduce it (as minimally and precisely as possible)**:
Login, and notice the Orange Alert on the top. Close the alert. Log out and Login again.
Alert will still be visible
**Anything else we need to know**:

**Environment**:
garden.canary.k8s.ondemand.com

**Comment by grolu** [comment]
These information / warnings are configured by the landscape administrator. If we want to persist the state (closed) we have two things to consider:
- Where do we store this information. We currently have no place to store user data, we could store it in the local store of the browser
- How to differentiate between messages (which one is marked as seen), we could of course use as hash for identification, however an admin could configure identical messages at different times which he wants to reappear. Therefore we need some kind of uniq identifier.

@holgerkoser @petersutter I think we discussed this before?

**Comment by vlerenc** [comment]
BTW, can we take it (CoreOS Container Linux disclaimer) down by now @vpnachev @grolu @petersutter ?

**Comment by vpnachev** [comment]
No, there is still clusters running with CoreOS.
