### ISSUE TITLE
Have all Secrets editable in the Secrets tab

### ISSUE THREAD

**Issue by valentinvieriu** [gardener/dashboard#888]
**What would you like to be added**:
Iv'e used [this tutorial](https://gardener.cloud/documentation/tutorials/shoot_istio_dns_certs/) to have custom domain name for my cluster. At this moment I need to edit this secret via kubectl, and the other secrets regarding Cloud Providers tokens are available in UI.
Please allow the editing of all Secrets in UI
**Why is this needed**:
It will be consistent with the rest of the flow, and also more user friendly and accessible to modify in the future

**Comment by grolu** [comment]
We have already open issues for this, see here https://github.com/gardener/dashboard/issues/616 and here https://github.com/gardener/dashboard/issues/781
I'll close this issue in favor for the ones mentioned above.
