### ISSUE TITLE
Improve UI development ( dev experience ) by using Storybook

### ISSUE THREAD

**Issue by valentinvieriu** [gardener/dashboard#889]
**What would you like to be added**:
You should be able to work on UI without a backend server. Other projects in the same field see [octant](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md) ( see [meetup video](https://youtu.be/TDhTg6lRE-M?t=829) ) solving this by using Storybook to display just the components and views in isolation.
[Storybook](https://storybook.js.org/docs/react/get-started/examples) development is a common practice develop UI components, and display them and test them in isolation.

**Why is this needed**:
I've tried to run the dashboard locally to fix some issues / propose features and was very hard ( still don't have it running ) to start it up. Just following the [readme](https://github.com/gardener/dashboard/blob/master/README.md) and this [guide](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md) here is a lot to ask for a FE developer. 
There are other advantages of using a system like this, for regression testing, visual diff and [more](https://storybook.js.org/docs/react/workflows/visual-testing)

**Comment by grolu** [comment]
Hi valentinvieriu,
thank you for your comment. While we agree that having something like this in place makes total sense, adding this to our project in the current state would mean a massive development effort. We are currently seeing very little contribution activity from the community. While one could argue that the complicated development setup is one of the reasons, I think that there are currently just not that many people around that would like to contribute to the UI part. On the other hand, those people that really like to (and have a significant amount of time designated for development in our project, manage to get a development setup up and running. Some people even have an own gardener installation running which makes things easier of course.
So in the end we are only a team of 3 and just have no time to invest here (the ROI is too small, too). If we would start from scratch though, we'd may consider this.
