### ISSUE TITLE
Forbid two consecutive hyphens in project names

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#89]
See https://github.com/gardener/gardener/issues/164 for details. Please forbid two consecutive hyphens in project names.

**Comment by vlerenc** [comment]
But then (now or later), shouldn't we also change the forbidden `-` into a forbidden `--` for cluster names? If you make the modification in the Gardener, we can forbid `--` and don't have to forbid `-` anymore.

**Comment by rfranzke** [comment]
Right, thanks for reminding of that.

**Comment by petersutter** [comment]
Commit 23f4fdf03a73f843e92f5ac2f939ef38fc8cb5c7
(tagging did not work because of missing space)
