### ISSUE TITLE
Show Shoot status and readiness on detail page

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#90]
Currently, the shoot status and readiness is only visible on the shoot list. We should have a readiness and status section also on the detail page. Maybe make it an expandable section (like kubeconfig) and show a badge next to it if there is an issue with the cluster.
Doing so, we can also add the operation retry functionality (#45) to the detail page.

**Comment by vlerenc** [comment]
Sounds like a good plan. :-)

**Comment by petersutter** [comment]
![Screen Shot 2018-06-13 at 09.49.39.png](https://images.zenhubusercontent.com/5a269e418a75884b9089eebb/89f9bbd0-39db-4f22-b219-97b89f216949)

**Comment by petersutter** [comment]
![Screen Shot 2018-06-13 at 09.54.23.png](https://images.zenhubusercontent.com/5a269e418a75884b9089eebb/aad885a8-7cad-4061-b336-74bf5046e5b8)

**Comment by vlerenc** [comment]
Nice!
