### ISSUE TITLE
Seed does not match CloudProfile when no label is present

### ISSUE THREAD

**Issue by briantopping** [gardener/dashboard#906]
The contract on `CloudProfile.SeedSelector` is currently written as "An empty list means that all seeds of the same provider type are supported". But [this code](https://github.com/gardener/dashboard/blob/1538be54ab96c76b32f8c5ad556a195554d24056/backend/lib/services/cloudprofiles.js#L42) seems to filter out all seeds that do no have a matching label. In other words, I believe the seeds must have a label match for this code to properly add the seed to the `CloudProfile`/ seed name array tuple that is returned.

In testing, `Seed` objects without labels are not properly mapped to `CloudProfile` objects that only have the matching types and [this log message](https://github.com/gardener/dashboard/blob/1538be54ab96c76b32f8c5ad556a195554d24056/backend/lib/services/cloudprofiles.js#L69) appears in the dashboard logs.

**Comment by petersutter** [comment]
yes thanks for reporting, this needs to be enhanced.

https://github.com/gardener/gardener/blob/c1388c682c43421c764f3f5d40c4b52d411b3916/example/30-cloudprofile.yaml#L11-L16
