### ISSUE TITLE
Editor not opening full screen but appears as letter box

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#92]
The editor fails to open correctly because size calc interferes with animation (info provided by @holgerkoser).

**Comment by petersutter** [comment]
somehow the toolbar background color is still transparent (cannot reproduce on local dev environment).
The background color is still overwritten by the (global) style `#app footer` defined in Login.vue
![Screen Shot 2018-06-25 at 16.28.12.png](https://images.zenhubusercontent.com/5a269e418a75884b9089eebb/2a203d05-a444-4787-a500-aa4daf628aae)
