### ISSUE TITLE
No Readiness Chips

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#93]
I noticed a strange thing: A cluster of mine (created since a while) had no readiness chips and was in reconciliation when I opened the clusters list. Also when reconciliation was done, it had no readiness chips, although all looks fine in the status section. The chips only returned after I refreshed the page. Other clusters (in core) had readiness chips (but weren't reconciling when I opened the page).

<img width="1187" alt="screen shot 2018-05-25 at 06 48 24" src="https://user-images.githubusercontent.com/4974203/40530487-4d5230a6-5ff9-11e8-8a8d-475a39bccdae.png">

As said, status looks fine:
<img width="622" alt="screen shot 2018-05-25 at 06 48 35" src="https://user-images.githubusercontent.com/4974203/40530488-4e26c884-5ff9-11e8-9d34-b4faedccdc6e.png">

**Comment by petersutter** [comment]
just checked and could see the same behavior. But after waiting for a few seconds also the chips appear.
I also talked to Rafael and confirmed that it's a normal behavior as the healt checks are done from a different controller.
