### ISSUE TITLE
Improve Ticket link

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#949]
**What would you like to be added**:
![tickets](https://user-images.githubusercontent.com/5526658/108341850-68cce600-71da-11eb-8d9e-4abd1c64dda8.jpg)
When clicking on the ticket link it should either scroll directly to the ticket card on the shoot details or open the ticket on github itself.

**Why is this needed**:
Currently it only links to the shoot details page which does not add much value

**Comment by rfranzke** [comment]
It would also be nice to see the list of closed tickets for the same cluster in the shoot details page.

**Comment by dguendisch** [comment]
See also https://github.com/gardener/dashboard/issues/1005 for a feature request on showing closed tickets.
