### ISSUE TITLE
Add support for filtering per infrastructure provider

### ISSUE THREAD

**Issue by kon-angelo** [gardener/dashboard#994]
**What would you like to be added**:

While viewing a project, allow filtering of clusters based on the infrastructure provider.

**Why is this needed**:

In large projects with more than a few hundred clusters spread among all infrastructure providers it is hard to monitor clusters of only a particular infra. In this scenario simply sorting isn't very much helpful either. Hence it would be nice if I could apply one additional filter to reduce the results. This can be generalized as a feature for other columns with finite values e.g. `purpose` too.

**Comment by petersutter** [comment]
There is also a somewhat related issue regarding improving the search / filtering capability of the dashboard https://github.com/gardener/dashboard/issues/960
Maybe we need an umbrella issue for that @grolu
