### ISSUE TITLE
Shoot detail doesn't show OIDC kubeconfig if OIDC is enabled

### ISSUE THREAD

**Issue by javamachr** [gardener/dashboard#999]
**What would you like to be added**:
UI where one can see OIDC kubeconfig for endusers that would allow them to easily use it to access shoot.
**Why is this needed**:
Currently if OIDC is enabled for api server one has to create kubeconfig manually for endusers to let them use kubelogin with oidc.

**Comment by grolu** [comment]
As @petersutter mentioned here: https://github.com/gardener/dashboard/pull/1000#issuecomment-822437482
Let's wait until Gardener exposes the feature.

**Comment by grolu** [comment]
closed as this is a duplicate of #1596
